### ISSUE TITLE
[dbt 1.8] An error occured while initializing the dbt project: No module named 'dbt.adapters.factory'

### ISSUE THREAD

**Issue by anandgupta42** [AltimateAI/vscode-dbt-power-user#1029]
### Expected behavior

The functionality should work as it does in 1.7

### Actual behavior

An error occured while initializing the dbt project: No module named 'dbt.adapters.factory'

### Steps To Reproduce

@svipulrao98 Can you please add the steps to reproduce?

### Operating System

All

### dbt version

1.8

### dbt Adapter

Snowflake

### dbt Power User version

1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
dbt-adapters is an indepedent python lib now. https://github.com/dbt-labs/dbt-adapters/blob/1c137eec49e429eeb5551ca1525e14a5fd57e9d8/dbt/adapters/factory.py#L49 is the new home for method

**Comment by anandgupta42** [comment]
fixed in 0.39.5

**Comment by petersjanjaap** [comment]
pip install dbt-fabric did it for me, it adds the adapter for fabric. It's unfortunate it is imported into the cli functionality, because it requires you to install dbt-fabric, even though you are using a different db to interact with (say BigQuery.
