### ISSUE TITLE
Kill Terminal when only one terminal is open does not close the terminal panel

### ISSUE THREAD

**Issue by Firstero** [AltimateAI/vscode-dbt-power-user#1038]
### Expected behavior
Kill Terminal when only one terminal is open does not close the terminal panel
### Actual behavior
Kill Terminal when only one terminal is open does not close the terminal panel
### Steps To Reproduce
As code-server Kill Terminal when only one terminal is open does not close the terminal panel, I am very sure it's dbt power user extention caused this bug, I uninstalled it, the bug disappered
### Log output/Screenshots
https://github.com/microsoft/vscode/issues/165067
### Operating System
mac os 14.4
### dbt version
1.7.1
### dbt Adapter
trino
### dbt Power User version
0.37.0
### Are you willing to submit PR?
- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Closing as not being able to repro
