### ISSUE TITLE
Provide setting to disable setup walkthrough

### ISSUE THREAD

**Issue by matthieucan** [AltimateAI/vscode-dbt-power-user#1049]
### Describe the feature

Hi,
Thanks for the great extension!

I'm using dbt power user in dev containers, all pre-configured to work well with our dbt project.
However, when a new user starts, they are prompted with the setup walkthrough, and are confused as what to do (given the extension is already configured).
Would it be possible to have a setting to always disable the prompt, for environments where the extension is already pre-configured (such as dev containers, or projects containing the required settings in `.vscode/`)?

### Who will benefit?

Users working on dbt projects which already bundle the extension configuration.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
We have added a setting for this : https://docs.myaltimate.com/setup/optConfig/#disable-setup-walkthrough-pop-up
