### ISSUE TITLE
first query per session shows the settings page

### ISSUE THREAD

**Issue by OneCyrus** [AltimateAI/vscode-dbt-power-user#1081]
### Expected behavior

the query gets executed and the results are shown in the table

### Actual behavior

when pressing the "run" button 
![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/7747800/c17dc851-4bb7-4595-a6b0-0cac135d9f01)

the query results shows this

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/7747800/8ba487ef-3f44-46e1-8919-c756a1f26aa8)

### Steps To Reproduce

see actual behavior

### Operating System

Windows 11

### dbt version

1.7.13

### dbt Adapter

duckdb

### dbt Power User version

38.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@OneCyrus We will have a look soon.

**Comment by anandgupta42** [comment]
Fixed in version 0.39.18
