### ISSUE TITLE
The extension is not working properly on vs code. 

### ISSUE THREAD

**Issue by Vahid-flipside** [AltimateAI/vscode-dbt-power-user#1086]
### Expected behavior

Vs code startup should be without this error:
Skipping project: could not parse dbt_project_config.yml at 'file:///Users/vah/dataorg/dataorg': YAMLParseError: Flow sequence in block collection must be sufficiently indented and end with a ] at line 202, column 5: all_topics: [ '0x97116cf6cd4f6412bb47914d6db18da9e16ab2142f543b8fbd16b23a' ^

Also model child and parent models should show. 

### Actual behavior

Doesn't do any of the above 2 expected behaviours

### Steps To Reproduce

Install dbt power user extension on vscode.
Install dbt-bigquery on the machine. (MAC OS)

### Log output/Screenshots

<img width="1670" alt="image" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/98771482/cf4c02dd-89d0-44e1-bee4-35fceff33252">

### Operating System

MAC

### dbt version

1.6.13

### dbt Adapter

bigquery

### dbt Power User version

0.38.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Vahid-flipside** [comment]
<img width="1670" alt="image" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/98771482/3b41a448-d6de-4a9d-ba8d-ea9f9fad80a3">

**Comment by Vahid-flipside** [comment]
without the extension, dbt works perfectly fine.

**Comment by Vahid-flipside** [comment]
Sorry, where can I find this tab?

**Comment by Vahid-flipside** [comment]
Here is another screenshot that shows how parent and children models aren't showing
<img width="1670" alt="image" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/98771482/7ace82c8-8344-40c6-85fa-3e3a42450ca1">

**Comment by hrucchetto** [comment]
Hey, I have same error since some weeks ago.
Could you find a solution?

**Comment by mdesmet** [comment]
Can you post your dbt_project.yaml and the exact error you are getting (incl line number?)

**Comment by hrucchetto** [comment]
Skipping project: could not parse dbt_project_config.yml at 'file:///c%3A/Users/hugo.rucchetto/Desktop/projects/elephant-dbt': YAMLParseError: Flow map in block collection must be sufficiently indented and end with a } at line 47, column 1: }, } ^

**Comment by matthiasr** [comment]
The error I get is

```
Skipping project: could not parse dbt_project_config.yml at 'file:///Users/matthiasrampke/src/github.com/<redacted>/<redacted>': Error: Illegal argument: base
```

Under "Problems", I see "dbt configuration is invalid: No module named 'dbt'". There is also a popup that says "please ensure dbt is installed", however, trying to run that tries to install dbt in my Homebrew-managed Python, which doesn't allow messing with it.

What it _should_ be using is the Python from a venv in the project folder, which I _have_ selected using "Python: Select interpreter" at the folder level.

Other possibly related things:

* the Python backing the venv is installed with asdf (not the one from homebrew)
* when I open a terminal in VS Code, the venv is correctly activated and `dbt debug` passes
* the venv is correctly selected according to the indicator

I do not get these errors if I install `dbt-core` _globally_ instead, so I think this may have something to do with the venv? And then the config parsing error just happens as a consequence of dbt being "missing" altogether?
