### ISSUE TITLE
Project Not Detected

### ISSUE THREAD

**Issue by nikohunt** [AltimateAI/vscode-dbt-power-user#1089]
### Expected behavior

In VSCode:
- Pressing Cmd+Enter to run a query should show query preview
- Lineage of model should show when a model is open
- 'Defer to prod' Action has a dbt project dropdown which should show at least one dbt project
- 'Project Governance' Action has a Select Project dropdown which should show at least one dbt project
- Using any of the buttons in the top right with an open model (e.g., 'Run dbt Model') should result in that action being performed.

### Actual behavior

Instead
- Pressing Cmd+Enter in an open model results in nothing happening
- Lineage of model is entirely blank for any model file
- 'Defer to prod' Action shows no dbt projects
- 'Project Governance' Action has a Select Project dropdown which shows no dbt projects
- Using any of the buttons in the top right with an open model (e.g., 'Run dbt Model') results in nothing happening.

### Steps To Reproduce

- Install VSCode 1.89.0-insider 
- Use Sonoma 14.4.1 on 14" M1 Pro 2021
- Install any version of dbt Power User > v0.2.0 < v0.38.5

### Operating System

macOS 14.4.1 Build 23E224

### dbt version

1.7.11

### dbt Adapter

sql

### dbt Power User version

v0.38.5

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by suryaiyer95** [comment]
Hey @nikohunt. Thanks for submitting the issue

Few questions:
1. Which adapter/dialect are you using? (For example: snowflake)
2. Is the dbt tick mark shown in the bottom status bar?
<img width="619" alt="image" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/118222278/25f45315-ce17-45fe-b129-4520b28b5bce">

**Comment by nikohunt** [comment]
Hi @suryaiyer95 , thanks for the fast response.

1. PostgreSQL
2. Yes.

`dbt debug` also runs fine and, as mentioned, the whole set up works for v0.20.0.

**Comment by mdesmet** [comment]
Is this still an issue with latest version? Please reopen in case it is.
