### ISSUE TITLE
Implement Target Switching Feature in dbt Power User

### ISSUE THREAD

**Issue by polat-deniz** [AltimateAI/vscode-dbt-power-user#1106]
### Describe the feature

Please add a feature that allows users to quickly switch between different targets defined in profiles.yml directly within the dbt Power User extension. This feature should be similar to the --target flag in dbt CLI, enabling users to change the target on the fly for functionalities like query results and column-level lineage. This will prevent errors such as "Invalid object name" by allowing users to switch to the appropriate target environment without manually editing files or settings.

### Describe alternatives you've considered

As a workaround, I considered maintaining separate profile configurations and manually switching between these profiles by editing profiles.yml. However, this method is error-prone and inconvenient, especially when frequent changes are necessary.

### Who will benefit?

This feature will benefit dbt developers who manage multiple environments (e.g., development, production) within their projects. It allows for seamless transitions between these environments, enhancing productivity and reducing the risk of errors due to environment mismatches.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by divenyijanos** [comment]
Very similar to #124

**Comment by anandgupta42** [comment]
This feature was introduced in version 0.45.0. You can modify the target in the bottom panel next to the "defer" status icon.This feature was introduced in version 0.45.0. You can modify the target in the bottom panel next to the "defer" status icon.
![Screenshot 2024-09-19 at 11 58 43 AM](https://github.com/user-attachments/assets/04421ac2-1720-4315-90ed-39b9e58f1780)

**Comment by mattiamatrix** [comment]
@anandgupta42 this is not working for me using `dbt-trino`. I see the selector but it always queries the target I have defined in my `profiles.yml`

**Comment by mdesmet** [comment]
Can you add more information on you setup, as we fixed an issue with the target selection some time ago. It should work as expected.

**Comment by pekapa** [comment]
Same here, I have two targets with access to different schemas (all within Databricks) and changing the target-switcher has no effect and the default target is still used.
