### ISSUE TITLE
Ability to generate schemas.yml from sql query results

### ISSUE THREAD

**Issue by dharamsk** [AltimateAI/vscode-dbt-power-user#1118]
### Describe the feature

Since power user allows you to preview model results, I’d like the ability to generate schemas.yml with the query results. 

Running the command would generate a schemas.yml file with the tables and column names populated for the model. 

Ideally the command would parse the difference between an existing schemas.yml and the model results and add any new columns to schemas.yml. 

This is helpful when adding columns to have everything explicitly in the schemas.yml where I can then quickly add any tests or metadata.

Right now, I have to generate the schemas.yml manually, which is annoying and repetitive, especially when setting up a project or table for the first time. 

### Describe alternatives you've considered

I think there’s a dbt codegen utility that can do this, but it didn’t look super straightforward. 

### Who will benefit?

Anyone who generates schemas.yml by hand (most people I believe).

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Supported by the documentation editor.
