### ISSUE TITLE
Query runner: 'ConfigInterface' object has no attribute 'DEBUG'

### ISSUE THREAD

**Issue by rubenhelsloot** [AltimateAI/vscode-dbt-power-user#1134]
### Expected behavior

Since updating to dbt-core 1.8.0 and dbt-postgres 1.8.0, I cannot run queries using the Query Results view anymore.

When trying to run a query, I expect to see the result in the Query Results panel.

### Actual behavior

When trying to run a query, I get the following error:

```
{
  "code": -1,
  "message": "Error: There is a problem in your dbt project. Compilation failed: 'ConfigInterface' object has no attribute 'DEBUG'",
  "data": {}
}
```

### Steps To Reproduce

It triggers on any query, reloading or restarting the extension does not help. Removing `target/` does not help.

### Log output/Screenshots

I think vscode-dbt-power-user is for some reason not compatible with dbt 1.8.0 yet.

### Operating System

MacOS Sonoma 14.5

### dbt version

1.8.0

### dbt Adapter

dbt-postgres

### dbt Power User version

v0.39.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
fixed in v0.39.12
