### ISSUE TITLE
With `defer_to_prod` option, it raises

### ISSUE THREAD

**Issue by potsbo** [AltimateAI/vscode-dbt-power-user#1140]
### Expected behavior

With dbt 1.8 and `defer_to_prod` option set `true`, it shows no error in `PROBLEMS` tab.

### Actual behavior

`PROBLEMS` Tab at the bottom shows an error described below.

### `Copy Message` Result

> There is a problem in your dbt project. Compilation failed: Manifest.merge_from_artifact() got multiple values for argument 'other'

### `Copy` Result

```json
[{
	"resource": "/workspaces/<reducted>/dbt/dbt_project.yml",
	"owner": "dbt10",
	"severity": 8,
	"message": "There is a problem in your dbt project. Compilation failed: Manifest.merge_from_artifact() got multiple values for argument 'other'",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1000,
	"endColumn": 1000
}]
```

### Steps To Reproduce

- Clone https://github.com/potsbo/vscode-dbt-power-user-defer-issue-reproduce
- run `poetry install` in the repository
- open the repository in Visual Studio Code
- Update python interpreter to the venv created by poetry

#### Visual Studio Code version
```
ersion: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:32.757Z (1 wk ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```

#### poetry version

```
poetry --version
Poetry (version 1.8.2)
```

#### others

- It also happens on Codespaces
- I suspect https://github.com/dbt-labs/dbt-core/pull/9199, which I believe was released in dbt-core v1.8.0, caused this issue

### Log output/Screenshots

<img width="3120" alt="image" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/7638553/531e46ba-cbc6-4a72-87ce-c9eb4ee895a9">

### Operating System

macOS Sonoma 14.4.1 (23E224)

### dbt version

1.8.0

### dbt Adapter

dbt-bigquery 1.8.1

### dbt Power User version

v0.39.9

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Fixed in 0.39.12. Please reopen if not the case.
