### ISSUE TITLE
Change Build settings to make it easier to understand upstream and downstream

### ISSUE THREAD

**Issue by thewhitetulip** [AltimateAI/vscode-dbt-power-user#1166]
### Describe the feature

Build downstream -> Build downstream (model+)
Build upstream -> Build upstream (+model)
Build upstream and downstream -> Build upstream and downstream (+model+)

This makes it easier for everyone to understand what is upstream and downstream without having to accidentally building the entire project due to the confusion! Also this is how DBT Cloud works. So it'll keep the plugin consistent with the cloud UI

### Who will benefit?

People who are new to dbt power user

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Please make a PR, looks like a welcome change!

**Comment by thewhitetulip** [comment]
Cool, is there any instructions about how to build the project? I was able to find out where I have to make a change, the package.json file.

**Comment by anandgupta42** [comment]
Thanks for the contribution, @thewhitetulip
