### ISSUE TITLE
Query Results Horizontal Scroll Bar Hides at Low Heights

### ISSUE THREAD

**Issue by jaysobel** [AltimateAI/vscode-dbt-power-user#1172]
### Expected behavior

The `Query Results` pane `Preview` tab should always show a horizontal scroll bar if there are columns that do not fit in the width of the result box. 

### Actual behavior

In the default configuration of `Query Results` docked to the bottom of the window, and the `Preview` tab open showing results of a model test run, the horizontal scroll bar often gets 'pushed out' of the bottom of the frame when the panel is less than ~1/4 of the screen. See video to illustrate this better than I can explain it.

As a mouse user, I like having the scroll bar! I could also get use to using `shift + scroll`

The scroll bar also hover-highlights from *darker* on my dark mode theme ([Atom One Dark](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark)). Unclear if this is an issue with my theme. 

### Steps To Reproduce

With the `Query Results` pane docked to the bottom of the window and a wide table run in the `Preview`, resize the height of the pane below ~1/4 of the window height, or until the horizontal scroll bar disappears.

### Log output/Screenshots

https://github.com/AltimateAI/vscode-dbt-power-user/assets/22080862/2af5424c-5ded-45a9-b755-21c9d11dc9c3

### Operating System

macOS Sonoma Version 14.4.1 (23E224)

### dbt version

1.7

### dbt Adapter

Snowflake

### dbt Power User version

v0.39.15

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
Fixed in version 0.39.18

**Comment by jaysobel** [comment]
> Fixed in version 0.39.18

> 14 hours ago, +6,600 - 4,500, 46 files changed

t-thanks
