### ISSUE TITLE
Query Panel ignores {{ env_var() }} jinja in `profiles.yml`

### ISSUE THREAD

**Issue by quickcoffee** [AltimateAI/vscode-dbt-power-user#1197]
### Expected behavior

The extension should have read the specified environment variable via the [env_var function](https://docs.getdbt.com/reference/dbt-jinja-functions/env_var) to run a query against the database specified in the profiles file

### Actual behavior

Environment variable is not read and the query fails due to wrong credentials

### Steps To Reproduce

1. Specify the database PW in `profiles.yml` like this:  
`password: "{{ env_var('DB_PASSWORD') }}"`  

2. Run a query in the query panel

### Operating System

MacOS

### dbt version

1.8.1

### dbt Adapter

dbt-trino

### dbt Power User version

v0.39.19

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Did you follow the instructions on [docs.myaltimate.com/setup/optConfig#environment-variables-setup](https://docs.myaltimate.com/setup/optConfig/#environment-variables-setup)? Please reopen the issue if not succesful and add more reproduction details.
