### ISSUE TITLE
Documentation Editor Not retaining Tests

### ISSUE THREAD

**Issue by MLSteinw** [AltimateAI/vscode-dbt-power-user#1205]
### Expected behavior

when opening document editor it should read and display the current tests saved in the schema,
![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/58957727/c5b59a60-d9a0-4661-9833-fef3251a4afa)

These tests saved in this column should appear in the document editor.

### Actual behavior

It reads the descriptions but dose not read the tests and instead presents empty tests section.
![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/58957727/7be0770a-bfa2-4edd-8ac9-0cf101e0fda5)

### Steps To Reproduce

Generate documentation. 
add preidentified tests for column 
click save to the schema. 
switch focus to schema to confirm update. 
switch back to model and allow document editor to reload.
test will not be pressent. 

### Operating System

windows 10

### dbt version

1.7.16

### dbt Adapter

mssql

### dbt Power User version

v0.39.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@MLSteinw this has been fixed in version 0.40.0. Can you please confirm?

**Comment by MLSteinw** [comment]
@anandgupta42  looks to be working as expected on my end. thanks for the fix.
