### ISSUE TITLE
"Retrieving column level lineage" message keeps looping indefinitely

### ISSUE THREAD

**Issue by zoltanmihaly** [AltimateAI/vscode-dbt-power-user#1239]
### Expected behavior

Hey, I've just installed this extension and tried to use its column lineage feature as detailed here: https://docs.myaltimate.com/test/lineage/

### Actual behavior

When I select a column the "Retrieving column level lineage" message appears but it keeps looping indefinitely and I never see the lineage:

![dbt_power_user_error](https://github.com/AltimateAI/vscode-dbt-power-user/assets/29677433/2d3b3e12-2cb7-49b4-b2d1-d4c66c54d7bb)

### Steps To Reproduce

N/A

### Operating System

Windows

### dbt version

dbt Cloud CLI 0.37.11

### dbt Adapter

BigQuery

### dbt Power User version

v0.40.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@zoltanmihaly We are looking at it now. I'll have an update soon.

**Comment by zoltanmihaly** [comment]
@anandgupta42 Any updates on this? I'm still experiencing the same issue

**Comment by anandgupta42** [comment]
Hey @zoltanmihaly, it seems there is a performance issue on the dbt cloud cli side. If yes, can you please post a message in the slack channel - https://getdbt.slack.com/archives/C05KPDGRMDW ? This will help us involve the dbt cli team.

**Comment by anandgupta42** [comment]
@zoltanmihaly Can you please update to the latest version and let us know if this is still an issue?

**Comment by mdesmet** [comment]
Please reopen if not working as expected.
