### ISSUE TITLE
Query Results looping for infinite

### ISSUE THREAD

**Issue by mslamani-ext** [AltimateAI/vscode-dbt-power-user#1249]
### Expected behavior

preview the results of run model, by connecting with SSO to snowflake for the first time and keep the session alive for a while.

### Actual behavior

hello,
I am using a devcontainer on vscode with python:3.11-slim as docker image for my private project.
vscode version 1.90.2, dbt-core 1.8.0 dbt-snowflake 1.8.1, power user for dbt core v0.41.0
A proxy is configured, sucessfully i installed all the dependencies needed as well as dbt power user vscode extension.
the connection to snowflake is secured by SSO (azure active directory).
when i want to execute a dbt model using the 'query results', it tries to connect to snowflake after about 20 seconds then it is blocked! waiting a response or something else. but when i run dbt debug everything is well.
is there any ideas please about how to debug this or solutions ? thanks

### Steps To Reproduce

- run a model
- while running it connects with SSO to snowflake then keep the session a live. no need to reconnect for each model execution
- preview the results in Query Results

### Operating System

linux

### dbt version

1.8.0

### dbt Adapter

snowflake

### dbt Power User version

0.41.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
@AdiGajbhiye : Can you ensure that timeouts are stopping the execution and are displayed as error?

**Comment by mdesmet** [comment]
AFAIK this has been fixed already. Please reopen if not working as expected.
