### ISSUE TITLE
Improve the messaging for installing dbt

### ISSUE THREAD

**Issue by anandgupta42** [AltimateAI/vscode-dbt-power-user#1281]
### Describe the feature

When dbt is unavailable, we offer the user the option to install dbt. Sometimes, the user may have dbt installed but not in the Python environment selected for the extension. It would be helpful to inform the user of the Python path where dbt is located or provide a link to the FAQ page explaining the error in detail.

<img width="553" alt="Screenshot 2024-07-05 at 1 15 33 PM" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/93243293/a521c960-b35d-4ae2-9518-91b0f25fa234">

### Who will benefit?

Mostly the users who are setting up the extension for the first time.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by OneCyrus** [comment]
please add a setting to disable this message completely. see #854

i see so many people wasting time with this message just because the extension has a timing issue.

**Comment by anandgupta42** [comment]
@OneCyrus Can you clarify what do you mean by "the extension has a timing issue." ?

**Comment by anandgupta42** [comment]
The issue is that the user does not have dbt installed in the selected Python environment. So, technically the message is right.

**Comment by OneCyrus** [comment]
but in our case only for a few seconds. so the people try to troubleshoot the environment even though dbt is already installed.

**Comment by mdesmet** [comment]
Could you elaborate on your environment because it should not give any false alarm on dbt installed.  Are you using vscode locally or on codespaces? 

Every time the python interpreter is selected, the dbt installation is verified. Are you changing the python interpreter?

**Comment by OneCyrus** [comment]
@mdesmet we are using devcontainers (codespaces and locally).

the configuration is like below. after the devcontainer is built vscode automatically installs the dbt extension and also installs the dbt python module through the "postCreateCommand" in parallel. basically the dbt extension usually starts before the dbt python module is installed which leads to the missing dbt error. but a few seconds later dbt is then installed but most users already clicked on the dbt install button.

```
"postCreateCommand": "bash ${containerWorkspaceFolder}/init.sh",
"customizations": {
  "vscode": {
    "extensions": [
      "innoverio.vscode-dbt-power-user",
      ....
    ]
  }
}
```

**Comment by OneCyrus** [comment]
@mdesmet it should be pretty easy fix to just add an option to hide the "please ensure dbt is installed" dialog as a config setting.

**Comment by mdesmet** [comment]
Why are you not installing dbt in your devcontainer image itself? it will boot up your environment faster that way.

**Comment by mdesmet** [comment]
@OneCyrus : Please reopen if above solution is not working for you.
