### ISSUE TITLE
Lineage tab not available. Other features still working

### ISSUE THREAD

**Issue by cybersyn-cole** [AltimateAI/vscode-dbt-power-user#1283]
### Expected behavior

The lineage feature is not available in my IDE after using it with no problems for months. The rest of the Power User features still work.
<img width="1110" alt="Screenshot 2024-07-07 at 1 03 16 PM" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/169081019/8c8c3c76-9e6a-4e5f-a18d-ac570fbeae7f">

### Actual behavior

N/A

### Steps To Reproduce

N/A

### Log output/Screenshots

Already tried to resolve by:
- Uninstall/Reinstall Extension
- Reverting to an older version of the extension
- dbt clean/dbt deps
- Uninstall/Reinstall VS Code

### Operating System

Mac

### dbt version

Core: 1.8.2

### dbt Adapter

Snowflake

### dbt Power User version

v0.41.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cybersyn-cole** [comment]
Update: Got the tab to appear again by uninstalling VS Code and remove all information/setting about VS code/extensions from my device, but it just disappeared on me again

**Comment by anandgupta42** [comment]
@cybersyn-cole We are unable to replicate the issue. Do you have any other dbt related extensions installed that might be causing the conflict?

**Comment by josephberni** [comment]
Also having the same issue. Have tried uninstalling/reinstalling both the extension and the code editor but no luck.

**Comment by DavidfNZ** [comment]
Same issue for me. I dragged the lineage tab to the right hand side of VScode so it was to the right of my code, and the tab displayed as empty. Close the tab and now I can't find how to re-display the lineage.

**Comment by anandgupta42** [comment]
@DavidfNZ Right click on the tab bar and you should see an option to select the lineage panel.

![Screenshot 2023-12-01 at 8 51 08 PM](https://github.com/user-attachments/assets/6c7d1550-d7d4-4870-a113-0322cb32e487)

**Comment by anandgupta42** [comment]
@cybersyn-cole is this still an issue?

**Comment by cybersyn-cole** [comment]
No I haven't experienced an issue with this in about a month

**Comment by anandgupta42** [comment]
Thanks. Closing the issue.

**Comment by mspachecoagoro** [comment]
I have the same issue, already tried to reinstall vscode and vscode-dbt-power-user and it continues
![image](https://github.com/user-attachments/assets/00268870-379f-48be-a9bc-febe5c5b9daf)

**Comment by anandgupta42** [comment]
@mspachecoagoro Can you share the [devtools logs ](https://docs.myaltimate.com/trobleshooting/#developer-tools) and the [extension logs](https://docs.myaltimate.com/trobleshooting/#check-extension-logs) as well?

**Comment by devonds** [comment]
<img width="240" alt="image" src="https://github.com/user-attachments/assets/97b82b3a-cd34-469b-baa1-be71c26eb92f">
I also have this issue

**Comment by anandgupta42** [comment]
@devonds 
It seems the panel/view has been moved to a different location. You will have to reset the layout to get it back -

Here is how you can do it:
1. Open the command Pallet ( Ctrl + Shift + P ) for windows or (Cmd + Shift + P)  for mac
2. run the command  "View: Reset View Locations" (without the quotes)
It seems the panel/view has been moved to a different location. You will have to reset the layout to get it back -

Here is how you can do it:
1. Open the command Palette (Ctrl + Shift + P) for Windows or (Cmd + Shift + P) for Mac.
2. Run the command "View: Reset View Locations" (without the quotes).

Disclaimer:
1. This will reset the panel layout to factory default and will impact all the panels/views. It should be okay if you have created a custom layout of panels/views in VSCode.
Disclaimer:
1. this will reset the panel layout to factory default and will impact all the panels/view. It should be ok if you have done a custom layout of panels/views in vscode.

**Comment by Kit-Ok** [comment]
Thanks for everyone here, faced same issue and finally I could re-display the lineage tab by following the last @anandgupta42's instruction.
