### ISSUE TITLE
dbt configuration is invalid: Additional properties are not allowed ('flags' was unexpected)

### ISSUE THREAD

**Issue by mattia-m5t** [AltimateAI/vscode-dbt-power-user#1299]
### Expected behavior

After dbt core version update to v1.8.3, dbt power user is not working anymore with error:
`dbt configuration is invalid : Runtime Error at path []: Additional properties are not allowed ('flags' was unexpected) Error encountered in c:\myrepository\...\dbt_project.yml`

The error is shown in any tab (problems, lineage, document editor).

Our dbt core includes Elementary package, that in order to keep working required to set flags inside dbt_project.yml:
```
flags:
    require_explicit_package_overrides_for_builtin_materializations: false
```

### Actual behavior

N/A

### Steps To Reproduce

Set flags inside dbt_project.yml:
![image](https://github.com/user-attachments/assets/03bf83f6-b7ad-4c70-bb21-b21e0c802e49)

Already tried to resolve with no success by :

- Uninstall/Reinstall Extension (0.42.1)
- Reverting to an older version of the extension (0.41.0 , 0.41.5)
- dbt clean/dbt deps
- Restart VS Code

What actually has effect:
- Flags in dbt_project.yml seems unsupported as, if I comment those two lines -which is not an option in our case- and restart vscode, dbt power user then works correctly.

### Operating System

Windows

### dbt version

1.8.3

### dbt Adapter

dbt-snowflake

### dbt Power User version

0.42.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Works fine on my side on 1.8.3. My guess is that your python environment in the extension and in your terminal don't match.

<img width="719" alt="image" src="https://github.com/user-attachments/assets/65255861-baa6-4dd2-ab8b-cac0c6213f53">

**Comment by mdesmet** [comment]
You can run the diagnostics command and check for yourself if there is a dbt version mismatch:

<img width="638" alt="image" src="https://github.com/user-attachments/assets/96365374-bb6b-4efe-9402-e57a308da5c8">

**Comment by mattia-m5t** [comment]
hi @mdesmet, you are right, it's exactly what happened.
The diagnostics detected a different dbt version: 
![image](https://github.com/user-attachments/assets/0efc0a2b-1ae6-4e02-992d-3331c52df3a5)

Cleaning the python versions installed (I had multiple) and then choosing the right python interpreter solved my issue (vscode): 
![image](https://github.com/user-attachments/assets/f6d1eae9-c099-48b6-a0cf-e610f780d5a4)

Thanks a lot for your suggestion!
