### ISSUE TITLE
Improve Query Results for Json Objects

### ISSUE THREAD

**Issue by jlogan3** [AltimateAI/vscode-dbt-power-user#1308]
### Describe the feature

It would make Dbt Power User much easier to explore data and develop new models if there were some improvements to Query Results. 

1. **Truncate large column value**
Currently large column values span across making it really hard to view all of the columns in a query. It would be useful if large values were truncated. 

2. Beautify json objects
Because values span a single row, it makes it challenging to read, understand and then write statements to extract keys and values from objects.

Truncating + formatting objects would make using Power User much better. For now, I must explore data in dbt Cloud or Bigquery to get an understanding of the objects. 

[Video](https://www.loom.com/share/32fd790f667a4e228df3c29e5bda4c1d?sid=b8071014-2f5a-4177-91ea-f1061addb9a8)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jeff-skoldberg-gmds** [comment]
+1 on this.  If you want an example of what works well, the Snowsight UI does this pretty well.  Also dbt Cloud does it OK.  But my beef with dbt Cloud is that you can't expand the column width, so if you have a long column header it is truncated an you have no idea what the full column name is... awful.

Anyhow, I think a good UX is long values are truncated per the suggestion above, then you click on a cell and a window pops out on the right with the formatted JSON or full length long text.

**Comment by elliottrabac** [comment]
+1

**Comment by anandgupta42** [comment]
Thanks @jeff-skoldberg-gmds and @jlogan3 We will pick this up soon

**Comment by jeff-skoldberg-gmds** [comment]
It looks great!  Thank you.
