### ISSUE TITLE
dbt_project.yml Issue

### ISSUE THREAD

**Issue by ashleypaceRSF** [AltimateAI/vscode-dbt-power-user#1379]
### Expected behavior

My dbt project should load and my dbt_project.yml should have no issues.

### Actual behavior

Upon upgrading to version 0.44.2, my dbt_project file now has red lines under every row and if you hover over, you get this error message: dbt configuration is invalid : a string or stream input is required. If I drop my version back to 43.6, the issue goes away.

### Steps To Reproduce

Upgrade to version 44.2

### Log output/Screenshots

![image](https://github.com/user-attachments/assets/10db472c-8b5d-462e-9015-1cce58fe4a94)
![image](https://github.com/user-attachments/assets/0a82573c-c057-4525-89ee-7aecd64d94d1)

### Operating System

Windows

### dbt version

1.3.5

### dbt Adapter

Not sure

### dbt Power User version

0.44.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@ashleypaceRSF, could you downgrade to version 0.43.X to see if it resolves the issue? Also, did you intend to specify dbt version 1.3.5? It seems quite outdated.

**Comment by ashleypaceRSF** [comment]
> @ashleypaceRSF, could you downgrade to version 0.43.X to see if it resolves the issue? Also, did you intend to specify dbt version 1.3.5? It seems quite outdated.

@anandgupta42 yes I downgraded and that does resolve the issue. And yes, I am on version 1.3.5. I'm a team of one and I haven't had time to do any upgrades on our underlying infrastructure. I know it needs to be updated.

**Comment by ashleypaceRSF** [comment]
@anandgupta42 I downgraded to 43.6. I haven't tried any of the versions between 43.6 and 44.2 though to try and pinpoint the change. I can do that if it will help.

**Comment by anandgupta42** [comment]
There is an ongoing discussion about this issue - https://github.com/AltimateAI/vscode-dbt-power-user/discussions/1242

This first appeared on June 21st, so I am not sure if it has something to do with the latest version and only a subset of users are facing it.

We have not been able to reproduce the issue on our end so any help to pinpoint which release may have caused it will be really helpful. Also, in the discussion we have a posted a script to generate additional stack trace, can you please run it and paste the result to help us debug futher?

**Comment by ashleypaceRSF** [comment]
@anandgupta42 weird. I didn't get this issue until last week. I did just check, upgrading to version 44.0 causes the issue to occur. I will look at the script later and see what I can do.

**Comment by anandgupta42** [comment]
We have just released a fix. Please update to version 0.44.3 and confirm if the issue is resolved.

**Comment by ashleypaceRSF** [comment]
@anandgupta42 it's working as desired now! Thank you!!
