### ISSUE TITLE
Setup Issue post clicking : Validate Project

### ISSUE THREAD

**Issue by rohitpatilgenmills** [AltimateAI/vscode-dbt-power-user#1414]
Hello Team, 

I use dbt cloud. In the last step of configuration wherein we have to click validate project button. I get this issue. Can you please help me.

Encountered an error loading local configuration: dbt_cloud.yml credentials file for dbt Cloud not found. Download your credentials file from dbt Cloud to `C:\Users\G678097\.dbt`

**Comment by anandgupta42** [comment]
This is not a bug but a configuration issue with the local setup. The problem message is self-explanatory. Please try to fix the local setup and make it work with dbt CLI using the terminal. The extension should automatically start working.
