### ISSUE TITLE
legacy LINEAGE panel is not displayed. 

### ISSUE THREAD

**Issue by solavrc** [AltimateAI/vscode-dbt-power-user#1430]
### Expected behavior

The legacy LINEAGE panel should be displayed.

### Actual behavior

The legacy LINEAGE panel is not displayed. 
The extension runtime detects an uncaught error.
> ENOENT: no such file or directory, open '/home/vscode/.vscode-server/extensions/innoverio.vscode-dbt-power-user-0.45.1/lineage_panel/index.html'

### Steps To Reproduce

Attempt to display the legacy LINEAGE panel in versions v0.44.9 and later.

### Log output/Screenshots

![image](https://github.com/user-attachments/assets/49626a28-dd07-48d0-9016-199ccfa1c3d4)

I will submit a PR shortly.
**Note**: You can use the New UX (Beta) by setting `"dbt.enableNewLineagePanel": true`.

### Operating System

Debian GNU/Linux 12 (bookworm)

### dbt version

1.8.6

### dbt Adapter

none

### dbt Power User version

0.44.9+

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@solavrc We are planning to deprecate this panel soon. Can you let us know if there is anything missing in the new panel that's making you revert to the old panel?

**Comment by anandgupta42** [comment]
fixed in 0.45.2

but the panel will be deprecated soon. Please let us know the reason why you have not moved to the new panel.
