### ISSUE TITLE
Documentation Editor - Creating tests as "tests" instead of "data_tests"

### ISSUE THREAD

**Issue by joshrodgersKA** [AltimateAI/vscode-dbt-power-user#1449]
### Expected behavior

When using the documentation editor to create tests, tests are expected to be created with the "data_tests" property.

### Actual behavior

When using the documentation editor to create tests, tests are being created with the "tests" property, which is deprecated.

### Steps To Reproduce

Open the documentation editor, add data tests, inspect created yml.

### Operating System

Windows 11

### dbt version

dbt Cloud CLI - 0.38.15 (Versionless)

### dbt Adapter

Fabric

### dbt Power User version

v0.46.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by saravmajestic** [comment]
@joshrodgersKA is this happening while creating tests for model or column? Do you mind record a video for us to validate the issue?

**Comment by joshrodgersKA** [comment]
https://github.com/user-attachments/assets/75f1e796-41a2-474c-9f5e-81127a04ded6

@saravmajestic - I'm seeing it happen when creating tests for columns. I've attached a video. Let me know if you need anything else. Thanks!

**Comment by saravmajestic** [comment]
Thank you @joshrodgersKA Video is really helpful. I have identified the issue and will release a fix soon
