### ISSUE TITLE
[DocsFeedback] Column Lineage - /test/lineage/

### ISSUE THREAD

**Issue by paul-cunningham-jt** [AltimateAI/vscode-dbt-power-user#1473]
These 2 sentences are contradictory:
You need to add an API key to view column level lineage. 
You can view model level lineage without an API key.

**Comment by ppradnesh** [comment]
I am not sure I understand the contradiction. With model-level lineage, you can only see how models are connected, and you don't require an API key for that. If you need to see how columns are connected, column-level lineage comes in, and it requires an API key.

**Comment by mdesmet** [comment]
This is more of a discussion, not a feature request or bug. Let's keep this section for issues only.
