### ISSUE TITLE
Add more features to webview

### ISSUE THREAD

**Issue by tomsej** [AltimateAI/vscode-dbt-power-user#182]
### Describe the feature

Currently, the result set of the query contains a simple HTML table, which is wonderful! It would be even better to support some advanced functions here.

### Describe alternatives you've considered

I have been using [https://perspective.finos.org](https://perspective.finos.org) with great success, that allows not only showing the Table but filtering + visualization.

### Who will benefit?

Everyone who use result sets.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
@tomsej : Let me know how i can help you to contribute!

Feel free to ping me on dbt Slack.
