### ISSUE TITLE
Support target-path with Jinja macro (eg `{{ env_var('DBT_TARGET_PATH', 'target') }}`)

### ISSUE THREAD

**Issue by KyleWellendorff** [AltimateAI/vscode-dbt-power-user#189]
### Expected behavior

I would expect right clicking on a jinja REF statement and hitting "Go To Definition' would take me to the parent model. My tests/parent/child models also never populate in the extension window on the left pane. Perhaps an issue with the manifest.json file. It also is not running DBT LIST anymore on file changes. Made sure my file extensions are associated to jinja-sql and that I didnt have DISABLE DBT LS option enabled

### Actual behavior

Nothing happens except I get this in the logs:

`Could not read manifest file at c:\Users\Kyle Wellendorff\OneDrive\Documents\GIT\folder\folder\{{ env_var('DBT_TARGET_PATH', 'target') }}\manifest.json: Error: ENOENT: no such file or directory, open 'c:\Users\Kyle Wellendorff\OneDrive\Documents\GIT\folder\folder\{{ env_var('DBT_TARGET_PATH', 'target') }}\manifest.json'`

Then when I actually press on "go to references", this also appears in the logs:
`[2022-11-03 12:17:36.740] [exthost] [error] [innoverio.vscode-dbt-power-user] provider FAILED
[2022-11-03 12:17:36.740] [exthost] [error] undefined`

### Steps To Reproduce

I am honestly not sure to reproduce this

### Log output/Screenshots

![dbt power user](https://user-images.githubusercontent.com/97039375/199776454-a3879d8b-3c97-42ca-ad55-44dfa0464ac4.gif)

![image](https://user-images.githubusercontent.com/97039375/199777229-b88e0476-6f41-48c4-b224-1dfc4fba6a17.png)

### Operating System

OS Name:                   Microsoft Windows 11 Pro                                                                     OS Version:                10.0.22000 N/A Build 22000 

### dbt version

1.3.0

### dbt Adapter

bigquery

### dbt Power User version

0.8.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Setting a dynamic target path using jinja is currently not supported:

`{{ env_var('DBT_TARGET_PATH', 'target') }`

That's why the extension doesn't work for you.

**Comment by KyleWellendorff** [comment]
Thank you so much! changing to just 'target' worked great! thanks again
