### ISSUE TITLE
Error while trying to generate the model (from sources)

### ISSUE THREAD

**Issue by jfox-teine** [AltimateAI/vscode-dbt-power-user#270]
### Expected behavior

Should be able to click on 'generate model' in sources.yml and have a model generated.

### Actual behavior

An error occured while trying to generate the model. Runtime Error. Runtime Error - Cannot create cursor from closed connection.

I can execute sql, execute model and compile sql, so it can see my profiles.yml and connect to my databricks instance just fine.

### Steps To Reproduce

I'm simply navigating from root>project>models>sources>sources.yml and clicking on Generate Model, then an error occurs.

![image](https://user-images.githubusercontent.com/118938578/209414918-1ad84d8a-d95b-4f19-97aa-89b88375b369.png)

### Log output/Screenshots

![image](https://user-images.githubusercontent.com/118938578/209414821-c233189e-0e92-470b-8c32-8d968ae44bca.png)

I have my SQL datawarehouse on and just ran a query against it from Execute dbt SQL.

### Operating System

Windows 10

### dbt version

1.3.1 core, 1.3.2 databricks, 1.3.0 spark

### dbt Adapter

dbt-databricks

### dbt Power User version

v0.10.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by nacruzg** [comment]
That's exactly what's happening to me at the moment.

**Comment by ranjitparva** [comment]
I have made the changes to fix this but not sure how to send the pull request. I have no access to push to origin branch to create a pull request.

**Comment by romiof** [comment]
Hello guys!

I can confirm that it still happen.

My versions:
dbt Power User v0.13.0
VS Code 1.78.2

Core:
  - installed: `1.4.6`
 Plugins:
  - sqlserver: `1.4.3` - Up to date!

**Comment by alittlesliceoftom** [comment]
I get the same issue.  So adding a vote

Dbt synapse 1.3.0

**Comment by stephan-meier** [comment]
Same error here.

dbt SQL-Server 1.4.6, Ubuntu 22

**Comment by cs-emre** [comment]
same error.

**Comment by DSamuylov** [comment]
Same error.

**Comment by MarvinJohannisson** [comment]
Same here. At random times i have not understood, it just starts working. But usually get this error. Also get same error when tryinh to synchronize columns with database in documentation editor.

**Comment by jagomezdiez** [comment]
Same here, mysql.
errors during documentation editor query update and Generate model

**Comment by mdesmet** [comment]
Is this still an issue? If so, please reopen.
