### ISSUE TITLE
Model autocomplete adds extra quotes when used within snippet

### ISSUE THREAD

**Issue by jnoynaert** [AltimateAI/vscode-dbt-power-user#301]
Works as intended: type out `{{ ref('` and then autocomplete a model name.

Works as intended: use `ref` snippet, delete the placeholder text, then `ctrl`+`space` to autocomplete.

Adds extra quotes: use `ref` snippet, then autocomplete a model name. See below.

![Code_rr8RM59Cxn](https://user-images.githubusercontent.com/5920864/216503064-1e53eae3-d3cf-43ec-909d-591225c79ea4.gif)

I suspect something to do with the text passed into https://github.com/innoverio/vscode-dbt-power-user/blob/afb20a36114bac931274de22635fc345668ad8ed/src/autocompletion_provider/modelAutocompletionProvider.ts#L46 changes in the snippet context?

**Comment by mdesmet** [comment]
That’s a bug indeed, will look into this in the coming days.

**Comment by romiof** [comment]
Hello guys!

I can confirm that it still happen.

My versions:
dbt Power User `v0.13.0`
VS Code `1.78.2`


BTW, this extension is really good 🚀
