### ISSUE TITLE
Query time never stops counting when running a query

### ISSUE THREAD

**Issue by sicarul** [AltimateAI/vscode-dbt-power-user#390]
### Expected behavior

I'd expect the query timer to stop after the query returns data

### Actual behavior

The counter keeps increasing, it's not the end of the world but it's a bit annoying and i can't see execution times

### Steps To Reproduce

Run a query

### Log output/Screenshots

https://user-images.githubusercontent.com/4952116/227932803-34c5bdfd-3753-4de4-af83-62eddded6abe.mov

### Operating System

Mac OS X Ventura 13.2.1

### dbt version

1.4.5

### dbt Adapter

Snowflake 1.4.2

### dbt Power User version

0.11.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
@jlpjavi : Are you still working on this?

**Comment by rafafr** [comment]
+1, same here

**Comment by anandgupta42** [comment]
@rafafr is this behavior consistent?

**Comment by DSamuylov** [comment]
Voting up. It would be great if this is fixed.

**Comment by DSamuylov** [comment]
Thank you so much for your answer, @anandgupta42. Before it was consistent, but I updated my Mac last night, and now I cannot reproduce the issue anymore. Strange, but I am happy it is resolved now. If I encounter the issue again, I will report.
