### ISSUE TITLE
Run Model additional commands

### ISSUE THREAD

**Issue by dlawin** [AltimateAI/vscode-dbt-power-user#396]
### Describe the feature

I would like to extend the dbt run command with an additional command (not just arguments)

Example: `dbt run && data-diff --dbt`

### Who will benefit?

Those who use dbt power user in conjunction with data-diff https://github.com/datafold/data-diff

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Please provide a PR, what you propose seems useful!

**Comment by dlawin** [comment]
> Please provide a PR, what you propose seems useful!

Awesome, I'm aiming for sometime this week!

**Comment by jonomillin** [comment]
This would be awesome! Following along for progress :)

**Comment by mdesmet** [comment]
@dlawin : Were you able to get it working? 

Please come over to dbt Slack to #tools-dbt-power-user if you need help.

**Comment by mdesmet** [comment]
Let's keep it open, maybe other people can help out!
