### ISSUE TITLE
"Generate Models" quick button doesn't include columns (with BigQuery?)

### ISSUE THREAD

**Issue by wtfzambo** [AltimateAI/vscode-dbt-power-user#416]
### Expected behavior

When clicking on "generate models" from a `sources.yml` file, the model is created but without any column.

For the record, everything else works (e.g. previewing a query result).

### Actual behavior

When clicking on "generate models" from a `sources.yml` file, the model is created including the columns.

### Steps To Reproduce

- Initialize a new dbt project with BigQuery as backend
- Add some fake data
- Create `sources.yml` file pointing
- Click "Generate model"

### Log output/Screenshots

<img src="https://user-images.githubusercontent.com/47462792/234043571-99e32ee9-a641-4571-ac74-319c31aaa27f.gif" width=70%>

### Operating System

Windows 11 and WSL2 on Ubuntu 20.04

### dbt version

1.4.6

### dbt Adapter

BigQuery 1.4.3

### dbt Power User version

0.12.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by christopher-leigh** [comment]
I am also experiencing this same issue, but with Snowflake!

**Comment by mdesmet** [comment]
Is this still the case with latest version? Please reopen if still the case.
