### ISSUE TITLE
"Detecting dbt" spins forever when opening file outside dbt workspace

### ISSUE THREAD

**Issue by thomasaarholt** [AltimateAI/vscode-dbt-power-user#418]
### Expected behavior

I would expect that when opening a specific sql file in VS Code, the extension finds dbt and reports it as present in the status bar, rather than spins forever:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/2721423/234668301-a18bb5c8-a1a3-44c8-acd9-57b25c881825.png">

### Actual behavior

I open a specific dbt model from the terminal (`code path/to/my/dbt_model.sql`), dbt is not found, despite me having set the path to the python interpreter correctly (afaik). These are my settings in VSCode:
```json
    "dbt.dbtPythonPathOverride": "/Users/thomas/oda/dbt-models/.direnv/python-3.9.9/bin/python",
    "dbt.profilesDirOverride": "/Users/thomas/oda/dbt-models",
```

I observe no output at all in the OUTPUT -> "Log - dbt" window.

If I open the root folder (`code dbt-models`) first, and then open the same dbt model in that workspace, everything works as expected

### Steps To Reproduce

Open a dbt model directly in vscode, e.g. `code path/to/my/dbt_model.sql`

### Operating System

Mac OS Ventura 13.0

### dbt version

1.3.2

### dbt Adapter

snowflake

### dbt Power User version

v0.12.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
dbt detection is not related to the selected file but just to the selected python interpreter. However it should not continue to keep spinning.

Is this still an issue in the current version?

**Comment by mdesmet** [comment]
Please reopen if still an issue.
