### ISSUE TITLE
Allow setting an ignore list for where to not look for dbt_project.yml files

### ISSUE THREAD

**Issue by alex-at-loom** [AltimateAI/vscode-dbt-power-user#419]
### Describe the feature

I develop our dbt project in a vscode dev container. as part of that process, dbt packages are built into the project repo. some of them like `dbt_utils` contain a `dbt_project` file.

when opening the project in vscode the following warning appears:
```
dbt Power User detected a project located in /workspaces/***/packages/dbt_expectations/integration_tests that is contained inside another project /workspaces/loom-dbt. This is an unsupported configuration. If you believe this is a valid configuration, please open a github issue.
```

it would be excellent if, in the extension settings I could write an ignore path like `"packages/*"` to have the extension not look for/include/parse `dbt_project` files in that folder (or others in the workspace, potentially).

### Describe alternatives you've considered

Honestly, couldn't think of any

### Who will benefit?

Folks who have multiple `dbt_project.yml` files in their workspace. It would not only remove the warnings (nice to have) build would also improve (potentially significantly) performance!

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
I have removed this check in master as I provided some other logic to deal with nested projects.

It will soon be released.

**Comment by alex-at-loom** [comment]
Thank you so much @mdesmet!

**Comment by alex-at-loom** [comment]
@mdesmet I noticed that the feature as implemented didn't allow for or prevent parsing of deeply nested dbt projects, as I'm still receiving these errors crowding the output pane: 
<img width="910" alt="image" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/128755743/8e9f84e2-0af4-408d-921f-40cbdc7100a1">

**Comment by anandgupta42** [comment]
@alex-at-loom Can you give some instruction on how this can be reproduced?

**Comment by miyeung** [comment]
Hello,

I'm having the same issue @alex-at-loom, did you find a workaround?

@anandgupta42 here is a folder structure that generates the issue:
```
dbt_project/
        — models/
        - dbt_project.yml
        — modules/
                - package_1/
                        - models/
                        dbt_project.yml
                - package_2/
                        - models/
                        dbt_project.yml
```

With the config `packages-install-path: "modules"` in the top-level `dbt_project.yml`. The `dbt deps` installs the packages in the main dbt project, under the `modules` directory.

**Comment by miyeung** [comment]
FYI, I managed to fix the issue by providing the main `dbt_project.yml` path in the `Allow List Folder` configuration.

**Comment by mdesmet** [comment]
Please try out the prerelease version 0.28.5. This automatically takes into account your `packages-install-path` settings and ignores those projects in those paths.

**Comment by jmesterh** [comment]
Could we still add a config option for an ignorelist for dbt_project.yml files? We have a monorepo with a main dbt_project.yml at the root, and under that other projects with their own dbt_project.yml. Those dbt_project.yml are not meant to be parsed on their own (thay are packages of the parent) and they are incomplete (eg. missing profile, etc.) and show up red/error state in VScode..
