### ISSUE TITLE
Build command Additional Params are being interpreted as selection criteria

### ISSUE THREAD

**Issue by joeb-ps** [AltimateAI/vscode-dbt-power-user#434]
### Expected behavior

I set the Build Model Command Additional Params configuration option to "--defer --state ." . This should add this exact string with one additional space at the start to the end of the dbt build command. This should cause all references to models that I am not running in this command to defer to the references provided in my production manifest. This manifest is located in the same directory as the dbt project, hence the "." as the reference.

### Actual behavior

I receive the following non-fatal errors:

The selection criterion '--defer' does not match any nodes
The selection criterion '--state' does not match any nodes
The selection criterion '.' does not match any nodes

The build command then proceeds to run the requested dbt model but without the effect of the defer flag. Interestingly, I added a space to the start of the configuration option string (i.e. " --defer --state .") which caused the following error to be included as well as the previous:

The selection criterion '' does not match any nodes

This suggests to me that the options in the configuration string are being passed as individual nodes to the build command rather than as flags.

### Steps To Reproduce

Add this string to the Build Model Command Additional Params configuration option and try to run any model using the build model button.

### Log output/Screenshots

Executing task: dbt build --select [model]  --defer --state .
10:55:43  Running with dbt=1.4.5
10:55:46  Found 1694 models, 1461 tests, 28 snapshots, 4 analyses, 574 macros, 0 operations, 112 seed files, 1008 sources, 78 exposures, 0 metrics
10:55:46  The selection criterion '' does not match any nodes
10:55:46  The selection criterion '--defer' does not match any nodes
10:55:46  The selection criterion '--state' does not match any nodes
10:55:46  The selection criterion '.' does not match any nodes

### Operating System

MacOS 13.3.1 (22E261)

### dbt version

dbt core 1.4.5

### dbt Adapter

Bigquery

### dbt Power User version

0.13.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
See also https://github.com/innoverio/vscode-dbt-power-user/discussions/439

**Comment by mdesmet** [comment]
See also https://github.com/innoverio/vscode-dbt-power-user/issues/457

**Comment by wongway** [comment]
I found a workaround for this that may inform a bugfix. It looks like each param and param value needs to be its own line in the extension settings interface. I discovered this by injecting an extra `'` at the beginning of one of the parameters, which resulted in an error like this:

```
> Executing task: dbt run --select MODEL ' --profile PROFILE --target TARGET
  File "<string>", line 8
    dbt_cli.invoke(['run','--select','MODEL','' --profile PROFILE','--target TARGET','--profiles-dir',r'MYPROJECTDIR'])

SyntaxError: invalid syntax
```
