### ISSUE TITLE
Query Results Scaling

### ISSUE THREAD

**Issue by Yacobolo** [AltimateAI/vscode-dbt-power-user#438]
### Describe the feature

Hi is i possible do scale the query preview. Currently it is very large - ideally i would like to be able to scale it down and keep all other windows/panels at the same zoom level. Is there a workaround? 
<img width="776" alt="image" src="https://github.com/innoverio/vscode-dbt-power-user/assets/45033225/392c0b83-bbb8-42b7-865c-372c67a27980">

### Who will benefit?

People working on laptop / small screens

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
@Yacobolo : Could you have a try add supporting this? This shouldn't be that hard and should be doable through CSS.

**Comment by Yacobolo** [comment]
Ill give it a go!
