### ISSUE TITLE
LineageView panel max height cutoff

### ISSUE THREAD

**Issue by kirk-dave** [AltimateAI/vscode-dbt-power-user#446]
### Expected behavior

The `LineageView` viewContainer should scale with the Panel as it is expanded (eg: `Query Results` container does this)

### Actual behavior

The `LineageView` ViewContainer cuts off and does not scale with VS code's panel as it is expanded. This cuts off the lineage graph

### Steps To Reproduce

Open the Lineage View panel with a model that has an extreme number of children references

### Log output/Screenshots

![Screen Shot 2023-05-24 at 10 47 40 AM](https://github.com/innoverio/vscode-dbt-power-user/assets/92391208/5629040c-d545-421c-9977-91fe06f27c54)

### Operating System

macOs Monterery v12.3

### dbt version

1.5.0

### dbt Adapter

dbt-snowflake

### dbt Power User version

v0.13.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by kirkbrunson-dave** [comment]
I think this is related to the `lineage_panel.graph`'s [height defaulting to `500`](https://github.com/innoverio/vscode-dbt-power-user/blob/53cdc9e03fddad9445aec1e8962260dfe52e9959/lineage_panel/main.js#L8).

Let me know if not -- happy to contribute a PR here.

**Comment by mdesmet** [comment]
It probably is. Please make a PR!

**Comment by kirkbrunson** [comment]
Happy to -- do you have any contributing guides? I see the note in the README about needing to get set up.

**Comment by anandgupta42** [comment]
@kirkbrunson https://github.com/innoverio/vscode-dbt-power-user/blob/master/CONTRIBUTING.md

**Comment by anandgupta42** [comment]
closing this since the old lineage panel will soon be deprecated
