### ISSUE TITLE
Support using the extension without a database connection

### ISSUE THREAD

**Issue by jsnb-devoted** [AltimateAI/vscode-dbt-power-user#518]
### Describe the feature

I work at a larger organization that really wants the "offline" features that are driven by the manifest (eg autocomplete, lineage, go-to definitions etc) but cannot support connecting to the extension to the database. We maintain a wrapper around dbt that controls how we authenticate with our snowflake data warehouse and we can't inject that into the python process that runs the extension.

What we would want is to be able to use seamlessly use extension without our profile values actually being evaluated. This would effectively mean turning off the feature that [rebuilds the manifest](https://github.com/innoverio/vscode-dbt-power-user/blob/master/src/manifest/dbtProject.ts#L272) in the background.

### Describe alternatives you've considered

Our profile uses environment variables for the login credentials -- we tried setting them to empty strings like so:
```
  "terminal.integrated.env.linux": {
    "SNOWFLAKE_PASSWORD": "",
}
```
And this actually works except that because it is rebuilding the manifest in the background with a different value at `SNOWFLAKE_PASSWORD` dbt reads that as changing a profile environment variable. As soon as we go to run dbt we get:
```
17:31:58  Unable to do partial parsing because config vars, config profile, or config target have changed
17:31:58  Unable to do partial parsing because env vars used in profiles.yml have changed
``` 

### Who will benefit?

My team would love to use this but with 1800+ models we can't afford to do a full parse every time we run dbt in our development environments. I suspect we are something of an edge case but other large orgs that want the metadata features without the interactive features would use this.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
Hey @jsnb-devoted, Thanks for recommending this enhancement. We are looking forward to the PR. Let us know if you need any help.
