### ISSUE TITLE
Use Macro files directly for definitionProvider instead of waiting for Manifest file update

### ISSUE THREAD

**Issue by ranjitparva** [AltimateAI/vscode-dbt-power-user#540]
### Describe the feature

It take few seconds for Manifest file to be built. It would be nice if the macroDefinitionProvider directly depends on the fileWatcher.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
Looking forward to your PR, @ranjitparva. Let us know if you need any assistance.
