### ISSUE TITLE
Support full custom wrapper for dbt execution

### ISSUE THREAD

**Issue by jeff-orennia** [AltimateAI/vscode-dbt-power-user#565]
### Describe the feature

As part of our DBT workflow, we parse a file containing a bunch of variables, convert them into DBT vars and then invoke whichever DBT command we're running with --vars {parsed_variables}. Since these vars drives the output of the commands and interact with the contents of our dbt models, it's fairly important that they be included when calling DBT build/run/etc.

It seems like this would be possible if we were able to provide a full custom wrapper to dbt power user that would be invoked whenever a command was run and provided with the dbt command being requested. The wrapper would then be responsible for executing that command (and other any other steps required by the user's workflow).

### Describe alternatives you've considered

I looked into using the existing dbtPythonPathOverride functionality as the documentation around it suggests it can be used for a custom wrapper. However, I don't think it'd be particularly friendly for a custom wrapper since the args are python code that would be need to parsed to find the actual dbt command. It might be possible, but it'd be a pain.

### Who will benefit?

Anyone with a more complex DBT workflow that requires any pre/post processing before invoking the dbt commands.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jeff-orennia** [comment]
Having dug into the code more and realized how much runs through dbt_integration.py rather than directly through the Python interpreter (like run/build), I'm not sure this is as useful as I thought.

We found a way to work around our the issues on our end with external inputs so can get by without this. Feel free to close.

**Comment by mdesmet** [comment]
Just curious, how did you manage to solve your issue?
