### ISSUE TITLE
Running query preview goes to the wrong tab

### ISSUE THREAD

**Issue by Luttik** [AltimateAI/vscode-dbt-power-user#571]
### Expected behavior

@mdesmet just to have an issue for what we just saw during our debugging session. I think the title describes it perfectly.

### Actual behavior

For me running the query preview always results in the terminal tab having the focus.

### Steps To Reproduce

-

### Operating System

-

### dbt version

-

### dbt Adapter

-

### dbt Power User version

-

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Related issue : https://github.com/AltimateAI/vscode-dbt-power-user/issues/464

**Comment by mdesmet** [comment]
Related issue : https://github.com/AltimateAI/vscode-dbt-power-user/issues/428
