### ISSUE TITLE
Stop execution of a query

### ISSUE THREAD

**Issue by tdeenes** [AltimateAI/vscode-dbt-power-user#579]
### Describe the feature

When one uses the "Execute dbt SQL" feature, the execution can hang due to various issues, e.g. due to authentication issues or too resource-heavy queries. A simple solution would be to add a "x - Terminate execution" button to the tab where the spinner appears, which would just cancel the webview-process (as terminating a query is RDBMS-specific, so supporting it would require more work).

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@tdeenes We have rolled this fix in the latest pre-release version (v0.34.0). Please try it out and let me know if you have any feedback.

Just in case if you need, here is how to Install the Pre-Release:
- Navigate to the extension page within VSCode.
- Select "Switch to Pre-Release" or access the drop-down menu/cogwheel next to the install/uninstall buttons.
- Choose 'Install Pre-Release' from the available options.

**Comment by tdeenes** [comment]
@anandgupta42  Thank you for working on this. Here is the result of my test session:

- :ballot_box_with_check: Start a query against Snowflake without connecting to the internet, then cancel it
- :ballot_box_with_check: Start a heavy query, then cancel it:
   * sometimes it cancelled the query instantaneously, sometimes I still had to wait for a few seconds or had to click on 'Cancel Query' multiple times
- :negative_squared_cross_mark: Start a query on a non-existing source or ref, then cancel it
  * This query runs forever, 'Cancel query' does not help
  * In VSCode debug tool, I see the following exception: 
```
  [innoverio.vscode-dbt-power-user]Traceback (most recent call last):
  File "/home/appuser/.vscode-server/extensions/innoverio.vscode-dbt-power-user-0.34.0/dist/dbt_integration.py", line 590, in _compile_sql
    node = self._compile_node(self.get_server_node(raw_sql, temp_node_id))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.vscode-server/extensions/innoverio.vscode-dbt-power-user-0.34.0/dist/dbt_integration.py", line 508, in get_server_node
    process_node(self.config, self.dbt, sql_node)
  File "/opt/pysetup/ifdagster/.venv/lib/python3.11/site-packages/dbt/parser/manifest.py", line 1756, in process_node
    _process_sources_for_node(manifest, config.project_name, node)
  File "/opt/pysetup/ifdagster/.venv/lib/python3.11/site-packages/dbt/parser/manifest.py", line 1729, in _process_sources_for_node
    invalid_target_fail_unless_test(
  File "/opt/pysetup/ifdagster/.venv/lib/python3.11/site-packages/dbt/parser/manifest.py", line 1328, in invalid_target_fail_unless_test
    raise TargetNotFoundError(
dbt.exceptions.TargetNotFoundError: Compilation Error
  Sql_Operation 'sql_operation.sunbasket.t_da7dc4a1d5534d87802818cb946ba3f9' (from remote system.sql) depends on a source named 'foo.tabbbllle' which was not found
```

**Comment by anandgupta42** [comment]
@tdeenes thanks for testing the pre-release! Could you please let me know which operating system you used to test it?

**Comment by tdeenes** [comment]
Docker, [python:3.11-slim](https://github.com/docker-library/python/blob/105d6f34e7d70aad6f8c3e249b8208efa591916a/3.11/slim-bookworm/Dockerfile)

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
```

```
$ code --version
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

**Comment by anandgupta42** [comment]
@tdeenes We pushed a fix for "Start a query on a non-existing source or ref, then cancel it" use-case. Please update to version 0.34.1 to check if the issue is resolved.

**Comment by tdeenes** [comment]
@anandgupta42 I can confirm everything works as expected. Thank you for this great tool!
