### ISSUE TITLE
Large numbers get truncated and final digits replaced with 00s when using Execute dbt SQL

### ISSUE THREAD

**Issue by louis-vines** [AltimateAI/vscode-dbt-power-user#583]
### Expected behavior

I have recently noticed that when you run `Execute dbt SQL` against a jinja sql file and there are large numbers in the results any numbers larger than 17 digits get their final digits replaced with 000s.

I am using snowflake as my backend.

## Reproducable example

Create a sql file:

```
select 123456789123456789123 as id
```

This will return:

|   id  |
| ---- |
| 123456789123456800000 |

### Actual behavior

If you run the same thing through the snowflake ui (or indeed the official snowflake plugin in vscode) you get:

```
select 123456789123456789123 as id
```

|   id  |
| ---- |
| 123456789123456789123 |

as expected

### Steps To Reproduce

 See my description above

### Log output/Screenshots

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/10738810/4db76626-f101-4944-a9d5-900a4429b250)

### Operating System

macos

### dbt version

1.6.1

### dbt Adapter

Snowflake

### dbt Power User version

0.17.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
This issue with large numbers being rounded in the query results is likely due to the limitations of JavaScript's Number data type. JavaScript uses 64-bit floating point numbers to represent numbers, which can accurately represent integers up to 15 digits long. Any integer larger than that may lose precision.

I will push out a fix soon.

**Comment by anandgupta42** [comment]
@louis-vines could you please upgrade to v0.31.4 and check if the issue has been resolved?
