### ISSUE TITLE
Parse additional manifest.json metadata for sources and macros

### ISSUE THREAD

**Issue by jsnb-devoted** [AltimateAI/vscode-dbt-power-user#594]
### Describe the feature

Once https://github.com/AltimateAI/vscode-dbt-power-user/pull/585 goes thru there will be hover capabilities for refs and sources. The `ref` hover box is rich with information because the `NodeParser` parses the descriptions/columns from the manifest. Sources and Macros only parse the paths so that go-to definition can be supported. If we get descriptions and columns for sources then those hover boxes can provide that metadata.

### Who will benefit?

This saves folks time of having to go-to the model and open the schema.yml file to see the descriptions/schema info for a source.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Hey @jsnb-devoted, can you have a look at this? This would be a really great addition and probably not difficult to add?

**Comment by jsnb-devoted** [comment]
I guess I already did it! I’ll close the issue.
https://github.com/AltimateAI/vscode-dbt-power-user/pull/599
