### ISSUE TITLE
This doesn't work for CTEs, breaks with:

### ISSUE THREAD

**Issue by michael-pyne** [AltimateAI/vscode-dbt-power-user#605]
This doesn't work for CTEs, breaks with:
```python
[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'with'. (156) (SQLExecDirectW)
```

_Originally posted by @Trymzet in https://github.com/AltimateAI/vscode-dbt-power-user/issues/128#issuecomment-1680551838_

**Comment by thebroberts** [comment]
@michael-pyne I posted in the linked issue since it has legs in the search results but give this a try:
https://github.com/AltimateAI/vscode-dbt-power-user/issues/128#issuecomment-1738200787

**Comment by anandgupta42** [comment]
@michael-pyne Have a look at https://github.com/AltimateAI/vscode-dbt-power-user#dbtquerytemplate-for-ms-sql

Let me know if this solves your problem
