### ISSUE TITLE
Annoying (false alarm) errors caused by dbt packages

### ISSUE THREAD

**Issue by tin-homa** [AltimateAI/vscode-dbt-power-user#627]
### Expected behavior

VsCode doesn't show error (in Problem panel + notification when startup)

### Actual behavior

VsCode shows error (in Problem panel + notification when startup)

### Steps To Reproduce

- Have a dbt project with custom packages-install-path (for example in `dbt_project.yml` I have `packages-install-path: "dbt/packages"`)
- Install a dbt package under said path (`dbt_utils` in my case)
- Receive errors (in Problem panel + notification when startup)
<img width="662" alt="image" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/90271975/138e9dfe-27c6-4073-b542-730ac4db453c">

### Operating System

Ubuntu 20.04 (WSL2)

### dbt version

1.4.7

### dbt Adapter

redshift 1.4.0

### dbt Power User version

0.20.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lionsardesai** [comment]
Hi!

Thank you for filing this bug. We got a similar report and have fixed it in the next version. Can you please upgrade the extension and tell us if this is resolved. If not, I'll be happy to look into this again.

Thanks,
Shardul.

**Comment by tin-homa** [comment]
Hi Shardul.
Thanks for the response. I just updated to 0.21.1 and the Problem is still showing. I tried disable/re-enable (with vscode restart in between) but it's still the same.
