### ISSUE TITLE
Non-ascii characters are garbled when formatting code

### ISSUE THREAD

**Issue by l1xnan** [AltimateAI/vscode-dbt-power-user#630]
### Expected behavior

Normal formatting

### Actual behavior

Before formatting:
```sql
select  α  from β
```

After formatting:
```
select �� from ��
```
![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/6105390/2b5ade4a-56d8-4937-8f44-8c0ebede7a20)

### Steps To Reproduce

For content:
```sql
-- demo.sql
select  α  from β
```
Format current sql document: `shift` + `alt` + `f`

### Operating System

windows 11

### dbt version

1.6.5

### dbt Adapter

dbt-duckdb

### dbt Power User version

0.20.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lionsardesai** [comment]
Hi,

thank you for filing this issue. Having examples is very useful in verifying the issue.
Using the provided example, I tried going through the steps and was able to successfully see a formatted output.

For formatting purposes, the extension uses a python library called sqlfmt. 
The versions I used to verify this are listed below:

sqlfmt: 0.20.0  (using `shandy-sqlfmt-0.20.0`. The command to install is: `pip install 'shandy-sqlfmt[jinjafmt]'`)
python: 3.11 


If you have an older version of the package, please try installing this version and retrying.

sqlfmt also has an online reformatter where you can try out your exact sql if the example above does not cover all the cases:
https://sqlfmt.com/

Please let us know if there is anything further that we can do here.

**Comment by l1xnan** [comment]
@lionsardesai `α`, `β` is ok, but the Chinese characters are still wrong.

The code formatting failed for the following content:
```
   -- 中文(Chinese)
   -- α
   -- β
select α, 
`中文`, 
    β
from demo
```
DevTools Console error message:
```
console.ts:137 [Extension Host] 1 file had errors while formatting.
0 files passed formatting check.
-
    sqlfmt encountered an error: Could not parse SQL at position 47: '`�\udcad文`, 
    β
from demo'
```
------


For the following content:
```
   -- 中文(Chinese)
   -- α
   -- β
select *
from demo
```
format to:
```
-- �\udcad�\udc87(Chinese)
-- α
-- β
select * from demo
```
--------

On the terminal, run the `sqlfmt` command, and the result is normal:
```
> sqlfmt --version
sqlfmt, version 0.21.0
> sqlfmt analyses\demo.sql
1 file formatted.
0 files left unchanged.
analyses\demo.sql formatted.
```

I suspect there is a problem with the encoding of the parameters passed to `sqlfmt`.

**Comment by l1xnan** [comment]
Test `sqlfmt` command in powershell:

```bash
❯ echo "select *    from demo" | sqlfmt --diff --encoding ascii -
1 file failed formatting check.
0 files passed formatting check.
- failed formatting check.
--- source_query
+++ formatted_query
@@ -1 +1 @@
-select *    from demo
+select * from demo

❯ echo "select `中文`    from demo" | sqlfmt --diff -
1 file had errors while formatting.
0 files passed formatting check.
-
    Traceback (most recent call last):
... ...
UnicodeEncodeError: 'utf-16-le' codec can't encode character '\udcad' in position 65: surrogates not allowed
```

**Comment by l1xnan** [comment]
It is determined that `sqlfmt` has a problem with [stdin encoding](https://github.com/tconbeer/sqlfmt/blob/01a261b57d6602643182bd573a9397eb5b5d1823/src/sqlfmt/api.py#L302:L304) processing, which can be fixed by setting environment variables
```
PYTHONUTF8=1
```

If this issue needs to be fixed in the current plug-in, it needs to modify:
```diff
        await this.commandProcessExecutionFactory
          .createCommandProcessExecution({
            command: sqlFmtPath,
            args: sqlFmtArgs,
            stdin: document.getText(),
+            envVars: { "PYTHONUTF8": "1" },
          })
          .complete();
```
A better way is to be able to read the project environment variable configuration.

**Comment by mdesmet** [comment]
@l1xnan : I guess this is not yet fully resolved? Can you please reopen if that's the case?
