### ISSUE TITLE
Cant use dbt power user 

### ISSUE THREAD

**Issue by 8513421** [AltimateAI/vscode-dbt-power-user#647]
### Expected behavior

When I click the play button in the analysis file, I should receive a table with the result in the "query results" tab

### Actual behavior

Nothing happens. The button doesn't work. The result does not appear in the "query results" tab. There is only the default text:
Previewing Query
Press Cmd+Enter (Mac) or Control+Enter (Windows/Linux) to run a query. Highlight part of a query to preview only selection

Default Query Limit
Query preview is limited to 500 rows by default, this can be configured in Settings -> dbt Power User or via changing the input to the left which is synchronized with the VS Code setting

Dispatched SQL
This tab displays the compiled query sent to the database. You can copy to run directly in your database.

### Steps To Reproduce

I installed a virtual environment (I tried with venv and poetry). Then I activated it. Then I installed dbt-core and dbt-postgres. Then db init. I have a profile file with access to the database in the project folder. All dbt commands work. I assigned *.sql to jinja. The icons have changed but the buttons still don't work. Lineage doesn't work either.

### Operating System

linux, manjaro, qtile/xfce

### dbt version

1.6.5

### dbt Adapter

postgres

### dbt Power User version

0.21.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@8513421 Can you please update to the latest version of the extension and let me know if the problem still exisits?

**Comment by 8513421** [comment]
Great :) It works now.
