### ISSUE TITLE
Numerical values >2147483647 or <-2147483649 incorrect in new query results table

### ISSUE THREAD

**Issue by cwmuller** [AltimateAI/vscode-dbt-power-user#652]
### Expected behavior

When executing a query against BigQuery, returned numerical values greater than 2147483647 or less than -2147483649 should be displayed correctly in the new results preview table.

### Actual behavior

When numerical values are greater than 2147483647 or less than -2147483648, values are returned as -2147483648. This only occurs in the new query results UI. The legacy UI returns the correct values.

### Steps To Reproduce

Create a dbt model. Write and execute a query which selects a value greater than 2147483647 or less than -2147483649 and inspect the resulting data in the new query results preview tab.

### Log output/Screenshots

Incorrect results in new UI
![Skjermbilde 2023-10-18 kl  11 28 07](https://github.com/AltimateAI/vscode-dbt-power-user/assets/37556881/33bb4682-1a8e-486e-9e2e-46bcd8549a21)

Correct results in legacy UI
![Skjermbilde 2023-10-18 kl  11 28 13](https://github.com/AltimateAI/vscode-dbt-power-user/assets/37556881/cc918284-0c90-4c14-aa3b-037af4ce9568)

### Operating System

MacOS 13.4

### dbt version

1.6.3

### dbt Adapter

BigQuery 1.6.5

### dbt Power User version

0.21.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
related to #583

**Comment by AleksandrsJuskaVisma** [comment]
Facing the same issue on Windows as well

**Comment by anandgupta42** [comment]
@AleksandrsJuskaVisma and @cwmuller could you please upgrade to v0.31.4 and check if the issue has been resolved?

**Comment by cwmuller** [comment]
Yes, this has been resolved. Thanks!
