### ISSUE TITLE
Copy column name or value from query results table.

### ISSUE THREAD

**Issue by FlockOfSeagulls1** [AltimateAI/vscode-dbt-power-user#659]
### Describe the feature

It would be helpful to be able to select a column or field value into the clipboard to use in a model for testing or defining a join or something similar. 

### Describe alternatives you've considered

Export the query results and copy it from the export, kinda not a great alternative. 

### Who will benefit?

Anyone who deals with some high column tables that have very long field descriptions.  Like SAP ECC, some tables have hundred of columns to wade through.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
We have already fixed the issue. Can you please update to the latest version and confirm if the problem has been resolved?

**Comment by FlockOfSeagulls1** [comment]
Working now, thank you.
