### ISSUE TITLE
Query results adapts to panel height

### ISSUE THREAD

**Issue by EstelleBarnoud** [AltimateAI/vscode-dbt-power-user#664]
### Describe the feature

Query results seem to have a max height set up. This is great if using the default panel height, but this is a bit of a waste of space when previewing a table:
<img width="1792" alt="image" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/28601386/9fb835af-4447-4a3e-88da-531b7e05c8fc">

### Describe alternatives you've considered

Use more scrolling and see less at a time on my screen.

### Who will benefit?

All query results tab's users that adapts their panel height

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
Thank you for bringing this to our attention, @EstelleBarnoud. We will push out a fix soon.

**Comment by anandgupta42** [comment]
@EstelleBarnoud We have pushed a fix. Please upgrade to the latest version.

**Comment by EstelleBarnoud** [comment]
@anandgupta42 Amazing thank you ⚡  Just tested it out and it's working properly 🔥
