### ISSUE TITLE
Multiple Query Result Tabs Feature

### ISSUE THREAD

**Issue by Duncannn** [AltimateAI/vscode-dbt-power-user#683]
### Describe the feature

A feature that allows users to have multiple query result tabs open simultaneously. When working on analyses, users often execute different queries and need to switch between the results. This feature would retain the query results in separate tabs, eliminating the need to re-execute the query or update the data visualization pane each time. It would be similar to the BigQuery UI, where a query result for any executed BigQuery query is stored and can be revisited without re-execution.

### Describe alternatives you've considered

Currently, when switching between different query results, users must re-execute the query and update the data visualization pane. Another alternative could be having a history or cache of the recent query results which can be revisited, but this still doesn't offer the same level of convenience and efficiency as multiple tabs.

### Who will benefit?

This feature will benefit engineers, data analysts, and any other users who need to run and compare multiple queries concurrently. It will streamline their workflow and save time due to the need for repeated executions.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@Duncannn @rightx2 This feature was shipped in version 0.41.0.
