### ISSUE TITLE
Error highlighting

### ISSUE THREAD

**Issue by olly-writes-code** [AltimateAI/vscode-dbt-power-user#684]
### Describe the feature

The feature would flag errant commas, syntax errors, or invalid references to columns.

You can see an example of this when looking at [Fivetran's dbt-language-server Vscode extension](https://github.com/fivetran/dbt-language-server#error-highlighting)

![error-highlighting](https://github.com/AltimateAI/vscode-dbt-power-user/assets/7778402/2e373744-ec70-4078-b7db-e8c79eb67d0a)

### Who will benefit?

All users of the Power User package. This saves time on wasted dbt runs that will fail instantly

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by stlee-aurora** [comment]
I would love to see this feature implemented as well!

**Comment by anandgupta42** [comment]
This is a fantastic suggestion and will be really helpful for the broader community. @olly-writes-code I see that you are interested to submit a PR also. Feel free to drop us a message if you need help.

**Comment by anandgupta42** [comment]
@olly-writes-code, are you still planning to work on this issue? We would be more than happy to assist you in getting started.

**Comment by olly-writes-code** [comment]
I looked into it and I won't be able to dedicate time to this. Sorry!

**Comment by anandgupta42** [comment]
@stlee-aurora @olly-writes-code We launched this feature today. Please give it a try and let us know if you have any feedback.

[SQL Validation Feature](https://docs.myaltimate.com/test/sqlvalidation/)

**Comment by olly-writes-code** [comment]
Hi @anandgupta42 

Very cool! Thank you for this.

When testing, it raises an issue on the first parentheses for a statement that isn't in the file. Does this mean something is broken upstream?
![CleanShot 2023-12-11 at 14 01 27@2x](https://github.com/AltimateAI/vscode-dbt-power-user/assets/7778402/4995b2a5-3c8e-4db2-9d31-db1df31d6411)

Does the user need to do a dbt run to ensure this is accurate?

**Comment by suryaiyer95** [comment]
HI @olly-writes-code 

- This message indicates that in the sql, there is usage of the column `hour` which it could not find in the tables used in the sql or that it is referenced incorrectly in the sql. 

- It is shown at line 1, because there are multiple occurences of 'hour' and we are not sure which one is the possible issue.


On that note: I think we can work on improving the error message. Or having this information in the documentation. Thanks for trying it out!

**Comment by olly-writes-code** [comment]
@suryaiyer95 Ahh, okay in this instance, there aren't instances of hour in the SQL file.

I checked again and noticed this error message
![CleanShot 2023-12-11 at 19 51 28](https://github.com/AltimateAI/vscode-dbt-power-user/assets/7778402/0e08df94-e980-453d-8765-89d8bf59ab75)

**Comment by suryaiyer95** [comment]
@olly-writes-code  So we expect the parent models  of the model which we are validated to be materialized.

- We are working on making the message more descriptive and clear

**Comment by olly-writes-code** [comment]
Sounds good. Thanks for the clarity :)
