### ISSUE TITLE
Improve startup time till model lineage is visible

### ISSUE THREAD

**Issue by alangner** [AltimateAI/vscode-dbt-power-user#694]
### Describe the feature

I am noticing a significant startup time for the extension to load up to the point where it displays the model lineage.
I just measured it to take a bit more than 2min from when VSCode finished starting and showing the dbt power user icon, up to the point where in the dbt tab I can see the model relations and lineage etc. 

To me it seems that the extension performs a dbt compile as this takes 1min15s for us (we have around 1k models). 

Is it possible to optimize this by e.g. using the output files from a previous dbt compile? (Or maybe my assumption is wrong for which causes this delay.)

### Describe alternatives you've considered

I already tried to whitelist the folder of our dbt project in the extension setting but this helped only marginally

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
Thanks for creating the feature request @alangner. Could you let me know the version of dbt you are currently using, as well as the operating system? Thank you.

**Comment by alangner** [comment]
> Thanks for creating the feature request @alangner. Could you let me know the version of dbt you are currently using, as well as the operating system? Thank you.

We are using a debian based docker container ( google/cloud-sdk:slim / https://hub.docker.com/r/google/cloud-sdk/ ) to which we connect from VSCode via DevContainer. I started to measure the time it takes to have the lineage available from the point where the devcontainer is succesfully connected and the extensions have been loaded/activated).
dbt version is 1.6.6

**Comment by anandgupta42** [comment]
@alangner We released a new version, 0.24.1, to improve loading time. Please let us know if you notice any changes.

**Comment by alangner** [comment]
@anandgupta42  Just tested it. The delay is down to only a couple of seconds. So it works perfectly. Thanks a lot!
