### ISSUE TITLE
Add --defer and --favor-state toggles

### ISSUE THREAD

**Issue by jackwelty** [AltimateAI/vscode-dbt-power-user#701]
### Describe the feature

Many folks make use of `--defer` and `--favor-state` to build and run models but reference production dependencies upstream. It would be great if we could do this in power user too. I know we can set additional run and build args, but this is not super user friendly to add and remove when iteratively developing.

Instead, a toggle in the UI "Defer on/off" and "Favor state on/off" would be great. Users would have to specify a local filepath to let dbt find their production manifest file.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
This feature was shipped in version 0.35.3
