### ISSUE TITLE
Support for Model Versioning

### ISSUE THREAD

**Issue by cashel** [AltimateAI/vscode-dbt-power-user#709]
### Describe the feature

This extension does not seem to support dbt models that have been [versioned](https://docs.getdbt.com/docs/collaborate/govern/model-versions) (e.g., `<model_file_name>_v2.sql` with model config properties). 

Tests, parent/child models, and documentation that used to appear for a non-versioned model no longer appear once that model has been versioned. Do note that all of this does work from dbt itself, so the issue appears isolated to just this plugin.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by smitsrr** [comment]
Any update on this issue? It's starting to become a blocker in our versioning and migration work.

**Comment by anandgupta42** [comment]
@smitsrr We plan to pick this up later this month. I will keep you all posted.

**Comment by anandgupta42** [comment]
@smitsrr We estimated that implementing this requires a multi-week effort since we need to introduce a new identifier type for model nodes across the codebase.  We don't have the bandwidth to take this up in the next month or so. I will keep you posted if things change in the future.

**Comment by chetchavat** [comment]
hi, is there an update on this enhancement?

**Comment by MalteNiederstadt** [comment]
Both Lineage and documentation editor will not work for Versioned Models, i'd also greatly appreciate a fix

**Comment by wahlrkr** [comment]
Would greatly appreciate this feature, as currently using versioned models makes the lineage functionality of DBT Power User un-usable 🙏

**Comment by anandgupta42** [comment]
Hello @cashel @wahlrkr @MalteNiederstadt @chetchavat @smitsrr , in the latest release, we have added model version support, which is a significant change impacting almost all functionalities of the extension. We would greatly appreciate it if all of you could try it out and let us know if everything is working as expected. Thanks!

**Comment by MalteNiederstadt** [comment]
Lineage works great at first glance, i'll keep testing and report any issues.
Thanks for your efforts, appreciate it greatly.
