### ISSUE TITLE
There is no way to change the save file in the documentation editor.

### ISSUE THREAD

**Issue by cosmicangler** [AltimateAI/vscode-dbt-power-user#710]
### Expected behavior

There is a way to update the save file location in the documentaiton editor.

### Actual behavior

There is no way to change the file save location in the documentation editor.

### Steps To Reproduce

Save documentation to a file using the button.
Then try or change the yml file to a different one.

### Operating System

mac

### dbt version

1.6

### dbt Adapter

databricks

### dbt Power User version

current one

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
This has been fixed in #1050
