### ISSUE TITLE
Bigints out of range in the query results' new UI

### ISSUE THREAD

**Issue by david-whimsical** [AltimateAI/vscode-dbt-power-user#714]
### Expected behavior

Running

should return

test|
-|
1675679957658|

### Actual behavior

Running

```
select 1675679957658 as test
```

actually returns

test|
-|
-2147483648|

### Steps To Reproduce

Open a `.sql` file, and run 

```
select 1675679957658 as test
```

### Log output/Screenshots

This number does not seem "random", and I believe something is up with the new UI.

```
select 1675679960664
```
will also return the same value.

I also tried

```
select 1675679957658::bigint as test
```

A teammate did ask all-mighty ChatGPT:

> The value `-2147483648` is at the boundary of the integer range in many systems (including PostgreSQL, which Redshift is based on). The integer data type typically ranges from `-2147483648` to `2147483647`. If `colA` is a bigint, this shouldn't be an issue, but if there's any chance that `colA` is actually an integer, the query might not behave as expected. Ensure that `colA` is indeed a bigint.

Here is what we get in the new UI:
<img width="743" alt="Screenshot 2023-11-15 at 17 57 18" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/115995643/1207e3cc-134f-4b51-8fda-48a7142cee95">

while it works fine in the legacy UI:
<img width="481" alt="Screenshot 2023-11-15 at 17 56 22" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/115995643/1e3fd765-8606-4d4a-bb6e-b2354a2ff9fc">

We originally had the problem on a bigint column in our dwh.

### Operating System

MacOS Ventura 13.5.2 (22G91)

### dbt version

Core: 1.6.6

### dbt Adapter

Redshift: 1.6.2

### dbt Power User version

v0.24.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by gaurpulkit** [comment]
<img width="281" alt="Screenshot 2023-11-27 at 4 08 35 PM" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/30400626/62503b64-f203-45f8-a636-0fcf9f52fc4a">
This issue seemed to be fixed when I tested it.

**Comment by anandgupta42** [comment]
@david-whimsical, could you please test the latest version of the extension and let us know if this issue has been fixed?

**Comment by david-whimsical** [comment]
Hey @anandgupta42!

I'm still experiencing the problem with version `v0.27.0` – it seems like it's the latest available in my end, is that right?

<img width="368" alt="Screenshot 2023-12-04 at 12 42 11" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/115995643/7ad069b9-0381-4d70-9fb7-ea99feb6e695">


<img width="806" alt="Screenshot 2023-12-04 at 12 43 55" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/115995643/45d6382b-c964-4441-b93c-0876b718fff5">

**Comment by stegus64** [comment]
I have the same problem. I have tested with version 0.27.2

I use the dbt adapter for databricks

```
>dbt debug
10:02:32  Running with dbt=1.6.6
10:02:32  dbt version: 1.6.6
10:02:32  python version: 3.11.6
10:02:32  os info: Windows-10-10.0.22621-SP0
10:02:32  adapter type: databricks
10:02:32  adapter version: 1.6.6

```

**Comment by anandgupta42** [comment]
@stegus64 and @david-whimsical, we have fixed the issue across all dialects and adapters. Can you please upgrade to v0.31.4 and verify if the issue persists?

**Comment by david-whimsical** [comment]
Hey @anandgupta42 – well done, this is fixed! Thanks a ton 😊 

<img width="512" alt="Screenshot 2024-02-07 at 09 18 31" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/115995643/29be4ff1-c1ab-4dc5-b809-fa28a0275452">
