### ISSUE TITLE
Enabling column name to be in lowercase while documenting through DB column sync

### ISSUE THREAD

**Issue by paritoshg2010** [AltimateAI/vscode-dbt-power-user#729]
### Describe the feature

While writing the documentation, whenever we sync the column names with DB (Snowflake), it pulls & save in schema.yml file as Uppercase. I was wondering if would it be feasible to do this in lowercase ?

### Who will benefit?

Those who likes the column names to be in lower case :)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
This was pushed in version 0.39.11. We save the column name in lower case by default now. However, the setting can be overridden. More details [here](https://docs.myaltimate.com/setup/optConfig/#setup-altimate-api-credentials-using-environment-variables)
