### ISSUE TITLE
direnv environment variables not picked up

### ISSUE THREAD

**Issue by StevenGrzybowski** [AltimateAI/vscode-dbt-power-user#73]
When opening a dbt project folder in vscode with this extension, it gives the error 
```
Encountered an error while reading profiles:
  ERROR Runtime Error
  Compilation Error
    Could not render {{ env_var('SNOWFLAKE_USER') }}: Env var required but not provided: 'SNOWFLAKE_USER'
Encountered an error:
Runtime Error
  Could not run dbt
```
if you are using direnv for environment variables - is there a way to have the extension wait for environment variables to load from direnv? I have direnv hooks set up in my zshrc

**Comment by mdesmet** [comment]
Interesting, so it sets up some environment variables based on the path you are into the shell.

Currently we execute the dbt commands through executing a child process (node api), see https://nodejs.org/api/child_process.html

I'm not sure it's possible to support direnv unless we execute on a existing terminal, however there is currently no way to get output of command completion using direct execution on existing terminals and we depend on that. If you have any ideas that i could try out or if you are willing to dig deeper and provide a PR, please go ahead!

**Comment by mdesmet** [comment]
Hi @StevenGrzybowski,

In 0.5.8 we currently take over any environment variables setup in settings.json (terminal.integrated.env.<platform>).

See #84

**Comment by reubster** [comment]
Couldn't the extension inherit from python.envFile? 

 "python.envFile": "${workspaceFolder}\\.env",
 
 I suppose it's being activated before the python venv?

**Comment by mdesmet** [comment]
If this is supported by the Python vscode extension. Can you investigate how this is done there?

**Comment by mdesmet** [comment]
@reubster : We now take over the variables from the Python extension in 0.8.9. Let me know if it works.

I doubt however this will fi support for direnv (that's a whole other issue).

**Comment by mdesmet** [comment]
Maybe you can try with the Python path override?
