### ISSUE TITLE
"dbt is not installed" because "cannot import name 'DEFAULT_PROFILES_DIR' from 'dbt.flags'"

### ISSUE THREAD

**Issue by thomaslaber** [AltimateAI/vscode-dbt-power-user#737]
### Expected behavior

I wanted to activate the extension but even in the correct conda environment with dbt installed and working, it doesn't find the dbt extension. Python version 3.9.15, dbt 1.6.

### Actual behavior

Activating the extension promts an error: 
"An error occured while initializing the dbt project: cannot import name 'DEFAULT_PROFILES_DIR' from 'dbt.flags' (/data/home/xxx/yyy/miniconda3/envs/dbt/lib/python3.9/site-packages/dbt/flags.py)"

### Steps To Reproduce

Activate the VS Code extension 

### Log output/Screenshots

![grafik](https://github.com/AltimateAI/vscode-dbt-power-user/assets/1642710/8791c1d4-bfb5-408a-85ec-462df0b54e7e)
![grafik](https://github.com/AltimateAI/vscode-dbt-power-user/assets/1642710/b21f2418-0a58-4d00-bb05-26fe0e047f46)

### Operating System

linux

### dbt version

1.6

### dbt Adapter

oracle & snowflake

### dbt Power User version

0.11.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
This means that your vscode is outdated. You are not on the latest extension version. Please verify your vscode version and update/reinstall vscode.

**Comment by thomaslaber** [comment]
You are absolutely correct. Issue closed. Thanks.
