### ISSUE TITLE
DBT Power User no python interpreter installed

### ISSUE THREAD

**Issue by DanMawdsleyBA** [AltimateAI/vscode-dbt-power-user#741]
### Expected behavior

I have installed python and have been using the extension for a while but recently I get an error saying python interpreter not installed. This blocks me from running dbt commands via the extension when previously this worked fine. Lineage however still works.

### Actual behavior

Whenever I try to run any build or other commands dbt power user is not able to find my existing python interpreter

### Steps To Reproduce

Open vs code and open a dbt sql file and run the build command.

### Log output/Screenshots

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/134394384/473fd796-6150-4a7d-ac73-56d5ed568db2)

### Operating System

Windows

### dbt version

1.7

### dbt Adapter

1.7

### dbt Power User version

0.27

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DanMawdsleyBA** [comment]
Hi Apologies for the slow reply. I was able to get it working again but required me to setup a venv instead

**Comment by anandgupta42** [comment]
No problem. I'm trying to determine what may have caused the issue. Do you happen to use conda?
