### ISSUE TITLE
Cannot change adapter

### ISSUE THREAD

**Issue by ellenne** [AltimateAI/vscode-dbt-power-user#750]
### Expected behavior

I selected by mistake the Trino adapter instead I am on a Redshift DB. How can I change the adapter? I saw the window asking me ONLY the first time and I am not finding where I can revert this decision

### Actual behavior

I wrongly selected Trino as SQL adapter instead I am on a Redshift Database. Could you please take the information from the YAML file??????? I WRONGY selected and I cannot revert this, where is the option.

### Steps To Reproduce

You need to start from a VS code without the extension and you need to go through your selections. You select the wrong interpreter and you want to revert this. Impossible. !!!

### Operating System

Windows 11

### dbt version

1.5.0

### dbt Adapter

I should use Redshift - I am using Trino - would like to change

### dbt Power User version

0.27.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
Also, a new python environment can be created using the steps mentioned here : https://code.visualstudio.com/docs/python/environments#_creating-environments
