### ISSUE TITLE
Folder and Naming standards check using Project health check

### ISSUE THREAD

**Issue by mithungame** [AltimateAI/vscode-dbt-power-user#771]
### Describe the feature

Currently naming standards are verified using dbt packages like https://dbt-labs.github.io/dbt-project-evaluator/0.8/rules/structure/#model-naming-conventions
however it does not provide instant feedback to developers the way an ide can
project health check can be enhanced to support standardization checks like prefix suffix 

example

..stage/All models should be prefixed with **STG_**
..stage/PAYMENT/All models should be prefixed with **STG_PMT**
..mart/dimension/All models should be prefixed with **DIM_**

example 
Top level folder structure must include stage, mart

Enhance Project Health check to add such capability

### Describe alternatives you've considered

Using dbt project evaluator package - Does not provide instant feed back
Writing dbt macros - Not straight forward as graph node has to be looped for all objects 
custom code analyzing manifest.json - will be outside ide

### Who will benefit?

Most data project follows defined naming standards as dictated by their organization and they will benefitted.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
This was included in the project governance feature release. You can find more information about it at https://docs.myaltimate.com/govern/governance
