### ISSUE TITLE
dbt_project.yaml does not recognize string type in `+snowflake_warehouse`

### ISSUE THREAD

**Issue by jeremy-thomas-roc** [AltimateAI/vscode-dbt-power-user#792]
### Expected behavior

Declaring this value with a string should be valid at the folder level

### Actual behavior

`Incorrect type. Expected "null".`

This error appears in all sections where this property is declared.

### Steps To Reproduce

add `+snowflake_warehouse` to any model in dbt_project.yaml

### Log output/Screenshots

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/104776437/98e857cc-300b-41eb-9e0e-0aea75c77b1d)

### Operating System

macOS 14.2 BuildVersion: 23C64

### dbt version

1.4.5

### dbt Adapter

dbt-snowflake

### dbt Power User version

0.28.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@jeremy-thomas-roc The errors seems to be coming from a different extension

![Screenshot 2023-12-22 at 1 20 17 PM](https://github.com/AltimateAI/vscode-dbt-power-user/assets/93243293/acf42d05-06f7-4961-b4c3-5e2e6af890aa)

**Comment by cmcnicoll** [comment]
That error is from [dbt-jsonschema](https://github.com/dbt-labs/dbt-jsonschema).

**Comment by jeremy-thomas-roc** [comment]
Whoops, will open there, thanks
