### ISSUE TITLE
Autocomplete issues on MacOs

### ISSUE THREAD

**Issue by antoine-lefebvre** [AltimateAI/vscode-dbt-power-user#804]
### Expected behavior

Autocomplete should work as described in https://docs.myaltimate.com/develop/autocomplete/

- typing ref inside curly brackets should create a ref() placeholder and autocomplete should propose the list of models
- typing source inside curly brackets should create a source placeholder and autocomplete should propose a list of databases first and then a list of source tables

### Actual behavior

A few issues happen:
- additional curly brackets are added when using the autocomplete inside curly brackets to add a ref our source
- the ref placeholder created from the auto-complete includes single quotes by default and auto-complete is not proposed within those single quotes. When deleting the single quotes then the auto-complete works
- autocomplete is not proposed for source macro regardless of the quotes being there or not

### Steps To Reproduce

- type "{{ ref" and select "ref" from auto-complete menu. this will result in "{{ {{ ref('') }} }} with the cursor after the first single quote
- type anything inside {{ ref('<cursor_here>') }}. This won't trigger auto-complete menu to show up
- type anything inside {{ source('<cursor_here>','') }}. This won't trigger auto-complete menu to show up

### Log output/Screenshots

![ezgif-5-64052257ef](https://github.com/AltimateAI/vscode-dbt-power-user/assets/88425531/efd8ef2c-a190-4ac5-8578-c4daacd80808)

### Operating System

macOs

### dbt version

1.5.3

### dbt Adapter

bigquery

### dbt Power User version

v0.28.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
The fix for 
"typing source inside curly brackets should create a source placeholder and autocomplete should propose a list of databases first and then a list of source tables" was pushed in version 0.38.4
