### ISSUE TITLE
Unable to use Build button pre release 0.28.5

### ISSUE THREAD

**Issue by DanMawdsleyBA** [AltimateAI/vscode-dbt-power-user#812]
### Expected behavior

Run a dbt model using the build button worked on the previous version 0.28.4

### Actual behavior

Fails with error

### Steps To Reproduce

Running on a windows machine using the extension version 0.28.5

### Log output/Screenshots

  File "<string>", line 8
    dbt_cli.invoke(['build','--select','crew_trip_work_code','--profiles-dir','c:\Users\u236618\Documents\Crew\olympus-oprn-crw-ops-planning\src\sql\snowflake\dbt\oprn_crw_ops_planning','--project-dir','c:\Users\u236618\Documents\Crew\olympus-oprn-crw-ops-planning\src\sql\snowflake\dbt\oprn_crw_ops_planning'])
                                                                                                                                                                                         ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

### Operating System

Windows

### dbt version

1.7

### dbt Adapter

Snowflake

### dbt Power User version

0.28.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
Thank you @DanMawdsleyBA for helping us test the pre-release version. We are currently working on a fix and will release an updated version soon.

**Comment by anandgupta42** [comment]
@DanMawdsleyBA  We released a new version 0.28.6. Can you please go ahead and check if it fixed your problem?
