### ISSUE TITLE
High CPU usage causing VS Code to be unstable

### ISSUE THREAD

**Issue by mcphillipsjohn** [AltimateAI/vscode-dbt-power-user#830]
### Expected behavior

Normal CPU Usage

### Actual behavior

After launching VS Code there is a warning dialog with the message: 
"dbt Power User detected 63 projects in your work space, this will negatively affect performance."

I suspect that the extension is detecting all the packages that my project uses in the dbt_packages folder as individual projects. 
My project has been like this for some time however, and I have never seen this warning message before.

### Steps To Reproduce

Open VS Code, open a folder containing a dbt project.

I suspect that the extension is detecting all the packages that my project uses in the dbt_packages folder as individual projects. 

### Log output/Screenshots

<img width="465" alt="Screenshot 2024-01-17 at 11 35 09" src="https://github.com/AltimateAI/vscode-dbt-power-user/assets/22888885/880b7b22-ed9c-405e-8c02-1119cb0735ea">

### Operating System

Ubuntu 20.04

### dbt version

1.4.9

### dbt Adapter

Snowflake

### dbt Power User version

0.29.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mcphillipsjohn** [comment]
I have rolled back to 0.28.4 and the issue has gone

**Comment by anandgupta42** [comment]
@mcphillipsjohn We released 0.29.2 with the fix. Please test and let us know if it resolved the issue.

**Comment by mcphillipsjohn** [comment]
> @mcphillipsjohn We released 0.29.2 with the fix. Please test and let us know if it resolved the issue.

Yes issue is resolved now - thank you.
