### ISSUE TITLE
dbt power user plugin checks dbt_packages

### ISSUE THREAD

**Issue by zwbill82** [AltimateAI/vscode-dbt-power-user#835]
### Expected behavior

It should not check the dbt_packages directory.

### Actual behavior

I install the dbt packages outside the project directory for common share. However, the latest version of the plugin will check this directory and display it in the "problems" tab. 
![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/29267289/f54d2779-3a8b-49c7-a156-07c468f50799)

### Steps To Reproduce

1. add package-install-path:  packages-install-path: "../dbt_packages"
`
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
packages-install-path: "../dbt_packages"
`
3. dbt deps
4. restart the vscode

### Log output/Screenshots

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/29267289/f54d2779-3a8b-49c7-a156-07c468f50799)

### Operating System

macos 12.4

### dbt version

1.6.9

### dbt Adapter

dbt-clickhouse-1.6.2

### dbt Power User version

v0.29.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
Hi @zwbill82, we have resolved the issue. Please upgrade to version 0.29.3 and let us know if the problem persists.
