### ISSUE TITLE
disable messages/notifications 

### ISSUE THREAD

**Issue by OneCyrus** [AltimateAI/vscode-dbt-power-user#854]
### Describe the feature

we would like to suppress these messages:

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/7747800/0a3b47b3-5e5b-4aaf-a90a-bd45dadfa0f8)

### Describe alternatives you've considered

looking for a setting of the extension to disable the notifications.

### Who will benefit?

codespaces/devcontainer users who get messages which are not relevant for them

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
The first one means that dbt is not detected. meaning the extension is not setup properly.

On the second one you have a point, I think this is currently not supporting codespaces setups by remembering the state.

**Comment by OneCyrus** [comment]
the main problem with the first one is that there is a timing issue with the extension installation and the installation of the dbt dependency. basically the extension starts before dbt is fully installed. this leads to people click on the install button even though dbt will be installed automatically a few seconds later. (the second issue with this is also that the extension doesn't detect dbt after the first failed attempt to find dbt and needs a complete restart of vscode)

**Comment by mdesmet** [comment]
@anandgupta42 : I think you solved that issue, could you advice here?

**Comment by mdesmet** [comment]
@anandgupta42 : Please provide your solution where you install dbt prior to launching vscode in codespaces.

**Comment by OneCyrus** [comment]
looks like others feel the same pain

https://github.com/AltimateAI/vscode-dbt-power-user/issues/1049

**Comment by anandgupta42** [comment]
We have added a setting to disable setup walkthrough:
https://docs.myaltimate.com/setup/optConfig/#disable-setup-walkthrough-pop-up
