### ISSUE TITLE
reload config after changes

### ISSUE THREAD

**Issue by OneCyrus** [AltimateAI/vscode-dbt-power-user#855]
### Describe the feature

when we change things like the sources.yaml the extension doesn't update until we restart vscode. would be great if changes are detected automatically and the extension reloads.

### Who will benefit?

users who work with dbt and extend the sources.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@OneCyrus, could you update to version 0.30.1 and confirm if the issue has been resolved?

**Comment by OneCyrus** [comment]
looks like this works now. thanks!
