### ISSUE TITLE
BigQuery Cost Estimate doesn't work with incremental tables & jinja call statements 

### ISSUE THREAD

**Issue by benjaminkaraoglan** [AltimateAI/vscode-dbt-power-user#862]
### Expected behavior

A Terminal Window called `Tasks - dbt` should have opened with a line saying `The query for table_name will process x MiB.`

### Actual behavior

An error occured, saying the dataset couldn't be found in EU Location (when the dataset does exist in EU location). Odd behavior is that the dataset name doesn't have the suffix name of the sub model you're trying to estimate your cost for (staging, intermediate or marts for example).
`An error occured while trying to compile your node: int_deava_enrichedRuntime Error 404 Not found: Dataset gcp_project:dataset_name_WITHOUT_SUBMODEL_SUFFIX was not found in location EU Location: EU Job ID: JOB-ID . If the issue persists, please [contact us](https://www.altimate.ai/support) via chat or Slack`

### Steps To Reproduce

To reproduce the issue, take any dbt code (stg/int/marts), you have in an existing dbt project that is not using incremental and/or jinja to make call statements, try the BigQuery Cost Estimate; and it should work. Once it works, modify the code for this very same table, and modify it to an incremental table, and perform a call statement at the begining to fetch the max date, and thus perform a filter for which dates to add to the table once the table is ran again as follows:

**Incremental settings:**
```
{{
    config(
        materialized='incremental',
        partition_by={
        "field": "dateFieldInDataset",
        "data_type": "date"
        },
        incremental_strategy = 'insert_overwrite',
        partition_expiration_days = 365
    ) 

}}
```

**Call Statement to fetch current max date in table:**
```

{%- call statement('latest_update', fetch_result=True) -%}

    SELECT
        MAX(SAFE.PARSE_DATE("%Y%m%d",partition_id)) as max_partition_id
    
    FROM `{{ this.database }}.{{ this.schema }}.INFORMATION_SCHEMA.PARTITIONS`
    
    WHERE table_name = "{{ this.identifier }}"

{%- endcall -%}

{%- set max_date = load_result('latest_update')['data'][0][0] -%}

```

**WHERE filter to add in order to select only new dates and add them to the table:**
```
 {% if is_incremental() and max_date is not none -%}
    
        WHERE dateFieldInDataset >= date_sub("{{ max_date }}", INTERVAL 1 DAY)

    {% endif %}
```

### Operating System

MacOS Sonoma 14.2.1 (23C71)

### dbt version

1.7.4

### dbt Adapter

dbt-Core

### dbt Power User version

v0.30.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
This should be supported in latest version. Can you please retest and reopen if not working?

**Comment by benjaminkaraoglan** [comment]
All good, now working fine. Thank you !
