### ISSUE TITLE
Fix NoneType' object has no attribute 'find_generate_macro_by_name' error

### ISSUE THREAD

**Issue by anandgupta42** [AltimateAI/vscode-dbt-power-user#866]
### Expected behavior

The user should be informed why the compilation has failed

### Actual behavior

The extension throws an error NoneType' object has no attribute 'find_generate_macro_by_name' when the underlying compilation has failed instead of letting user know the exact reason for the compilation failure

### Steps To Reproduce

add a macro that cannot be compiled and try executing a query it should fail with the above error

### Operating System

All

### dbt version

1.6+

### dbt Adapter

All

### dbt Power User version

0.30.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by DanMawdsleyBA** [comment]
I'm also getting this issue

**Comment by anandgupta42** [comment]
@DanMawdsleyBA The error is misleading, but there is an underlying compilation issue with your project that needs to be fixed. It should also show up in the Problems tab.

**Comment by ataft** [comment]
I was getting this issue and did what other people recommended `dbt clean` and `dbt deps`, but didn't find my issue until I tried `dbt compile`. After I fixed the compilation issue, I tried to clean and deps, but still had to close and re-open VS Code for this issue to go away.

**Comment by mdesmet** [comment]
Can you retest this with latest version. The problem should be shown in the problems panel. If the issue still persists feel free to reopen.
