### ISSUE TITLE
Runtime Error: dbt power user is failing when parsing contents of dbt-packages

### ISSUE THREAD

**Issue by sigveks** [AltimateAI/vscode-dbt-power-user#894]
### Expected behavior

Should not resolve the dbt_project.yml files within packages

### Actual behavior

Is resolving the dbt_project.yml files within packages - thus failing as profiles.yml is overridden in root.

### Steps To Reproduce

-Install newest version of extension
-Run 'dbt deps' in a terminal to install dbt packages
-Watch extension fail

### Log output/Screenshots

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/129047258/6c004415-57c9-4400-8271-623ef7183260)

### Operating System

Windows 10

### dbt version

1.7.7

### dbt Adapter

1.7.1 dbt-snowflake

### dbt Power User version

0.31.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
Hey @sigveks - We have pushed a fix in 0.31.7

**Comment by sigveks** [comment]
@anandgupta42 - Great! Seems to be working now, thanks!
