### ISSUE TITLE
250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting.  dbt debug shows 'All checks passed!'

### ISSUE THREAD

**Issue by roconno1** [AltimateAI/vscode-dbt-power-user#913]
### Expected behavior

I'm setting up dbt Power User for the first time and am able to successfully execute from terminal `dbt run` with `dbt debug` showing no errors.  When executing `SELECT * FROM {{ref("src_listings")}}` from inside VS Code, I would expect to see the query results.

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/57953334/695612ea-062f-44b5-aa42-924413b5f948)

### Actual behavior

When I try to use the query tool in dbt Power User I receive the following error:

Database Error
250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/57953334/e23c6340-eb4c-4fe2-96ba-b9b18caa33c1)

### Steps To Reproduce

The error occurs when I highlight the select statement and select play.
![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/57953334/69ec3a7e-5abd-40e9-8337-44d381a82c38)

### Operating System

Windows-10-10.0.19045-SP0

### dbt version

dbt version: 1.7.8

### dbt Adapter

Registered adapter: snowflake=1.7.1

### dbt Power User version

v0.33.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
It seems the extension has not been fully setup. 

Setup wizard: https://docs.myaltimate.com/setup/reqdConfig/

Also, I see four problems listed in the problem tab. Fixing those may solve the issue

**Comment by roconno1** [comment]
> It seems the extension has not been fully setup.
> 
> Setup wizard: https://docs.myaltimate.com/setup/reqdConfig/
> 
> Also, I see four problems listed in the problem tab. Fixing those may solve the issue

Thanks for the reply.  I went through the documentation and tried uninstalling/reinstalling the extension again with the same result.  I wonder if this could be a lead- when I execute `dbt debug` from my terminal inside VS Code I see everything passed, but when I click the Validate Project Setup button inside Setup dbt Power User it the connection test fails.  I lined up both outputs and everything matches (versions, .yml file locations, etc.), except for the failure when I try through Validate Project.  I hope this makes sense.  Any other suggestions?

**Comment by anandgupta42** [comment]
What is the error you are seeing for test failures? It's possible that you use ENV variables in your setup and those env variables are not available to the extension.

Do you see any issues in the problems tab?

You can chat with us [here](https://app.myaltimate.com/contactus) as well.

**Comment by roconno1** [comment]
Thanks.  The problems in the problems tab were spelling items that I added to Code Spell Check's dictionary to resolve (nothing config related).

Here are the test errors from setup wizard (Validate Project button):
![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/57953334/1c84af7e-b611-46f7-b7ff-a9e4776a1d33)

And this is what I see when I run from terminal:
![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/57953334/005ab497-32ad-4c5d-85fd-7d9b37efcdd1)

**Comment by anandgupta42** [comment]
Are you using environment variables to setup the profile or target?

**Comment by roconno1** [comment]
> Are you using environment variables to setup the profile or target?

I'm not sure- how do I check?

**Comment by mdesmet** [comment]
Closing as not being able to reproduce
