### ISSUE TITLE
Color highlighting missing from terminal output generated by the extension

### ISSUE THREAD

**Issue by anandgupta42** [AltimateAI/vscode-dbt-power-user#916]
### Expected behavior

Messages like sucess and other flags should be highlighted as is being done when executed in vscode terminal

### Actual behavior

Color highlighting is missing from the messages

### Steps To Reproduce

Perform any operations that outputs the result in the terminal

### Log output/Screenshots

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/93243293/6111a0bf-0dc0-4b64-a4b7-1e679cd47bc9)

### Operating System

Any

### dbt version

Any

### dbt Adapter

Redshift

### dbt Power User version

0.33.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
See also https://github.com/AltimateAI/vscode-dbt-power-user/issues/107

**Comment by anandgupta42** [comment]
I just checked on my mac and I see the colors. @jeff-skoldberg-gmds Which OS/Env are you on?

**Comment by jeff-skoldberg-gmds** [comment]
Windows 11 and Windows 10.

I thought I had the same issue with GitHub Codespaces as well but I have to check.

**Comment by Marcodenijs** [comment]
I'm experiencing the same issue, Windows server, snowflake adapter.

**Comment by jeff-skoldberg-gmds** [comment]
@anandgupta42 , I checked on github codesapces.  It is working as expected there.  So I guess the issue isolated to Windows.

**Comment by anandgupta42** [comment]
@Marcodenijs @jeff-skoldberg-gmds 

Can you do the following :

1. Set this on .vscode/settings.json
```
"terminal.integrated.env.windows": {
    "TERM": "xterm-256color"
}

2. Restart VSCode
3. Run any command.

Let me know if this fixed the issue.

**Comment by Marcodenijs** [comment]
@anandgupta42 

That did fix it for me! Thanks a bunch!

**Comment by anandgupta42** [comment]
Awesome.

The fix involves setting the TERM environment variable to xterm-256color in a VSCode terminal instance. This configuration instructs the terminal to operate in a mode that supports 256 colors and various text formatting options, enhancing the display of colored output. The TERM variable communicates the terminal's capabilities to applications, encouraging them to utilize full-color and formatting features.

This is related to VSCode and the underlying operating system's environment rather than something that should be hardcoded within the extension. It's better to keep it configurable using an environment variable. I will update the extension docs to include these instructions for windows users.

**Comment by anandgupta42** [comment]
Instruction added in the docs
https://docs.myaltimate.com/setup/optConfig/#enable-color-highlighting-of-terminal-output-on-windows

**Comment by jeff-skoldberg-gmds** [comment]
thank you @anandgupta42  and @mdesmet , that worked for me too!
