### ISSUE TITLE
Compile and other operation on selected code block ended up operating on the entire file

### ISSUE THREAD

**Issue by anandgupta42** [AltimateAI/vscode-dbt-power-user#917]
### Expected behavior

 Using the compile/play mouse shortcut for a selected section should compile the selected block

### Actual behavior

Only the selected code block should be executed or compiled

### Steps To Reproduce

Select a piece of code block and use the right click menu to select compile

### Operating System

Any

### dbt version

Any

### dbt Adapter

redshift

### dbt Power User version

0.33.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Closing as cannot repro
