### ISSUE TITLE
[DocsFeedback] Column Lineage - /test/lineage/

### ISSUE THREAD

**Issue by rifkiamil** [AltimateAI/vscode-dbt-power-user#934]
**Broken URL due to "4xw"**

Location: [Documentation page](https://docs.myaltimate.com/test/lineage/)
Issue: The URL is not working, possibly due to a typo ("4xw").
Suspected Cause: It seems like there might be a typo in the URL or the domain might have changed. The incorrect URL is https://wwww.altimate.ai/.

**404 Error on Self-Edit Link**

Location: The link to self-edit in the repository.
Issue: Clicking the link results in a 404 error page.
Broken Link: https://github.com/AltimateAI/vscode-dbt-power-user/raw/master/docs/test/lineage.md

**Comment by mdesmet** [comment]
@svipulrao98 : can you fix this？

**Comment by svipulrao98** [comment]
this is fixed
cc @ppradnesh
