### ISSUE TITLE
extension reports dbt project issues when dbt is not found (yet)

### ISSUE THREAD

**Issue by OneCyrus** [AltimateAI/vscode-dbt-power-user#948]
### Expected behavior

no errors when it can't find dbt

### Actual behavior

in addition to the error message from #854 we also have the problem that the extension reports errors on the dbt projects which block other projects in the same repo.

basically if dbt is installed after this extension in a devcontainer we have the problem with the notification but also we have some error messages reported as problems due to to the initialzation issue. imho it shouldn' report problems if it can't find dbt.

### Steps To Reproduce

have dbt projects in a repo and this extenion installed in vscode. when this extension can't find dbt (yet) it reports problems and blocks other debugger extensions in the same workspace.

### Log output/Screenshots

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/7747800/46a713b0-8706-47c3-8eec-844dc95246c7)

### Operating System

Debian 12

### dbt version

1.7.8

### dbt Adapter

duckdb

### dbt Power User version

v0.34.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
@anandgupta42 : Can you point the user to how to solve this issue?
