### ISSUE TITLE
sqlfmt does not format even with necessary parameters

### ISSUE THREAD

**Issue by darkcofy** [AltimateAI/vscode-dbt-power-user#957]
### Expected behavior

given the parameters:
```
"[jinja-sql]": {
		"editor.defaultFormatter": "innoverio.vscode-dbt-power-user",
		"editor.formatOnSave": true
	}
```

it is expcted that on save the .sql file will be autoformatted

### Actual behavior

file is not formatted nor is any error thrown

### Steps To Reproduce

create sql file , enter a valid sql statement and hit ctr+s.

### Operating System

Ubuntu 22.04.3 LTS

### dbt version

1.7.9

### dbt Adapter

dbt-athena

### dbt Power User version

v0.34.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@darkcofy We just release 0.34.6 that should take care of the issue. Let us know if the issue has been resolved.

**Comment by darkcofy** [comment]
issue has been resolved thanks!
