### ISSUE TITLE
Feature request: Show model and field documentation on hover

### ISSUE THREAD

**Issue by thomasaarholt** [AltimateAI/vscode-dbt-power-user#96]
It would be great if this extension extracted the model description and showed it in a python-docstring-like manner on hover (or cmd + shift + space). Data types would be great too, if available. 

Further, it would be great if this could apply to model columns as well, but I'm unsure if the extension is aware of which words in the model sql file are columns and which are not.

I'm happy to contribute in any way. From what I gather, dbt-power-user doesn't use the dbt python api, only calls command line arguments. Is that correct?

**Comment by mdesmet** [comment]
The extension would definitely benefit from some more focus on documentation related features.

**Comment by anandgupta42** [comment]
explore https://www.npmjs.com/package/node-sql-parser
